import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Starting seed...');

  // Clear existing data
  await prisma.userHistory.deleteMany();
  await prisma.favorite.deleteMany();
  await prisma.instruction.deleteMany();
  await prisma.ingredient.deleteMany();
  await prisma.substitution.deleteMany();
  await prisma.dish.deleteMany();

  console.log('✅ Cleared existing data');

  // Seed substitutions
  const substitutions = [
    { primaryIngredient: 'onion', substitutes: ['shallot', 'leek', 'scallion', 'green onion'], substitutionScore: 0.9 },
    { primaryIngredient: 'chicken', substitutes: ['turkey', 'tofu', 'seitan'], substitutionScore: 0.85 },
    { primaryIngredient: 'parsley', substitutes: ['cilantro', 'basil', 'chives'], substitutionScore: 0.8 },
    { primaryIngredient: 'lemon', substitutes: ['lime', 'vinegar', 'citric acid'], substitutionScore: 0.85 },
    { primaryIngredient: 'milk', substitutes: ['almond milk', 'oat milk', 'soy milk'], substitutionScore: 0.9 },
    { primaryIngredient: 'butter', substitutes: ['margarine', 'coconut oil', 'olive oil'], substitutionScore: 0.85 },
    { primaryIngredient: 'beef', substitutes: ['lamb', 'pork', 'mushrooms'], substitutionScore: 0.8 },
    { primaryIngredient: 'egg', substitutes: ['flax egg', 'chia egg', 'applesauce'], substitutionScore: 0.75 },
    { primaryIngredient: 'yogurt', substitutes: ['sour cream', 'greek yogurt', 'buttermilk'], substitutionScore: 0.9 },
    { primaryIngredient: 'rice', substitutes: ['quinoa', 'couscous', 'cauliflower rice'], substitutionScore: 0.85 },
    { primaryIngredient: 'soy sauce', substitutes: ['tamari', 'coconut aminos', 'worcestershire sauce'], substitutionScore: 0.9 },
    { primaryIngredient: 'tomato', substitutes: ['red pepper', 'tomato paste', 'sun-dried tomato'], substitutionScore: 0.8 },
    { primaryIngredient: 'garlic', substitutes: ['garlic powder', 'shallot', 'asafoetida'], substitutionScore: 0.85 },
    { primaryIngredient: 'ginger', substitutes: ['ginger powder', 'galangal', 'cardamom'], substitutionScore: 0.8 },
    { primaryIngredient: 'cream', substitutes: ['half-and-half', 'coconut cream', 'evaporated milk'], substitutionScore: 0.9 },
    { primaryIngredient: 'bread crumbs', substitutes: ['panko', 'crushed crackers', 'oats'], substitutionScore: 0.85 },
    { primaryIngredient: 'flour', substitutes: ['almond flour', 'coconut flour', 'rice flour'], substitutionScore: 0.8 },
    { primaryIngredient: 'sugar', substitutes: ['honey', 'maple syrup', 'agave nectar'], substitutionScore: 0.85 },
    { primaryIngredient: 'olive oil', substitutes: ['vegetable oil', 'canola oil', 'avocado oil'], substitutionScore: 0.9 },
    { primaryIngredient: 'wine', substitutes: ['broth', 'grape juice', 'apple cider vinegar'], substitutionScore: 0.75 },
    { primaryIngredient: 'cheese', substitutes: ['nutritional yeast', 'cashew cheese', 'vegan cheese'], substitutionScore: 0.8 },
    { primaryIngredient: 'pasta', substitutes: ['zucchini noodles', 'spaghetti squash', 'rice noodles'], substitutionScore: 0.85 },
    { primaryIngredient: 'lettuce', substitutes: ['spinach', 'arugula', 'kale'], substitutionScore: 0.9 },
    { primaryIngredient: 'mushroom', substitutes: ['eggplant', 'zucchini', 'tofu'], substitutionScore: 0.75 },
    { primaryIngredient: 'potato', substitutes: ['sweet potato', 'turnip', 'cauliflower'], substitutionScore: 0.85 },
  ];

  for (const sub of substitutions) {
    await prisma.substitution.create({ data: sub });
  }

  console.log('✅ Seeded substitutions');

  // Seed dishes
  const dishes = [
    // BREAKFAST (10 dishes)
    {
      name: 'Classic Pancakes',
      description: 'Fluffy buttermilk pancakes served with maple syrup and fresh berries',
      imageUrl: '/images/dishes/pancakes.jpg',
      category: 'breakfast',
      difficulty: 2,
      prepTime: 10,
      cookTime: 15,
      nutrition: { calories: 350, protein: 8, fat: 12, carbs: 52 },
      ingredients: [
        { name: 'flour', amount: '2', unit: 'cups', category: 'grain' },
        { name: 'milk', amount: '1.5', unit: 'cups', category: 'dairy' },
        { name: 'egg', amount: '2', unit: 'whole', category: 'protein' },
        { name: 'butter', amount: '3', unit: 'tbsp', category: 'dairy' },
        { name: 'sugar', amount: '2', unit: 'tbsp', category: 'sweetener' },
        { name: 'baking powder', amount: '2', unit: 'tsp', category: 'leavening' },
        { name: 'salt', amount: '0.5', unit: 'tsp', category: 'seasoning' },
      ],
      instructions: [
        { step: 1, text: 'Mix dry ingredients (flour, sugar, baking powder, salt) in a large bowl' },
        { step: 2, text: 'Whisk wet ingredients (milk, eggs, melted butter) in a separate bowl' },
        { step: 3, text: 'Pour wet ingredients into dry and mix until just combined (lumps are okay)' },
        { step: 4, text: 'Heat griddle to 375°F and lightly grease' },
        { step: 5, text: 'Pour 1/4 cup batter per pancake and cook until bubbles form, then flip' },
        { step: 6, text: 'Cook other side until golden brown, about 2 minutes' },
      ],
    },
    {
      name: 'Veggie Omelette',
      description: 'Fluffy egg omelette filled with fresh vegetables and cheese',
      imageUrl: '/images/dishes/omelette.jpg',
      category: 'breakfast',
      difficulty: 2,
      prepTime: 10,
      cookTime: 10,
      nutrition: { calories: 280, protein: 18, fat: 20, carbs: 8 },
      ingredients: [
        { name: 'egg', amount: '3', unit: 'whole', category: 'protein' },
        { name: 'bell pepper', amount: '0.5', unit: 'cup', category: 'vegetable' },
        { name: 'onion', amount: '0.25', unit: 'cup', category: 'vegetable' },
        { name: 'mushroom', amount: '0.25', unit: 'cup', category: 'vegetable' },
        { name: 'cheese', amount: '0.25', unit: 'cup', category: 'dairy' },
        { name: 'butter', amount: '1', unit: 'tbsp', category: 'dairy' },
        { name: 'salt', amount: '0.25', unit: 'tsp', category: 'seasoning' },
        { name: 'pepper', amount: '0.25', unit: 'tsp', category: 'seasoning' },
      ],
      instructions: [
        { step: 1, text: 'Beat eggs with salt and pepper' },
        { step: 2, text: 'Sauté vegetables in butter until softened' },
        { step: 3, text: 'Pour eggs into pan and swirl to coat' },
        { step: 4, text: 'When edges set, add vegetables and cheese to one half' },
        { step: 5, text: 'Fold omelette in half and cook until cheese melts' },
      ],
    },
    {
      name: 'Smoothie Bowl',
      description: 'Thick berry smoothie bowl topped with granola, fruits, and nuts',
      imageUrl: '/images/dishes/smoothie-bowl.jpg',
      category: 'breakfast',
      difficulty: 1,
      prepTime: 10,
      cookTime: 0,
      nutrition: { calories: 320, protein: 12, fat: 8, carbs: 58 },
      ingredients: [
        { name: 'banana', amount: '2', unit: 'whole', category: 'fruit' },
        { name: 'mixed berries', amount: '1', unit: 'cup', category: 'fruit' },
        { name: 'yogurt', amount: '0.5', unit: 'cup', category: 'dairy' },
        { name: 'almond milk', amount: '0.5', unit: 'cup', category: 'dairy' },
        { name: 'granola', amount: '0.25', unit: 'cup', category: 'grain' },
        { name: 'honey', amount: '1', unit: 'tbsp', category: 'sweetener' },
      ],
      instructions: [
        { step: 1, text: 'Blend frozen bananas, berries, yogurt, and almond milk until thick' },
        { step: 2, text: 'Pour into bowl' },
        { step: 3, text: 'Top with granola, sliced fruits, and drizzle with honey' },
      ],
    },
    {
      name: 'Avocado Toast',
      description: 'Toasted sourdough with mashed avocado, poached egg, and chili flakes',
      imageUrl: '/images/dishes/avocado-toast.jpg',
      category: 'breakfast',
      difficulty: 2,
      prepTime: 5,
      cookTime: 10,
      nutrition: { calories: 380, protein: 14, fat: 22, carbs: 34 },
      ingredients: [
        { name: 'sourdough bread', amount: '2', unit: 'slices', category: 'grain' },
        { name: 'avocado', amount: '1', unit: 'whole', category: 'vegetable' },
        { name: 'egg', amount: '2', unit: 'whole', category: 'protein' },
        { name: 'lemon', amount: '0.5', unit: 'whole', category: 'fruit' },
        { name: 'chili flakes', amount: '0.25', unit: 'tsp', category: 'seasoning' },
        { name: 'salt', amount: '0.25', unit: 'tsp', category: 'seasoning' },
      ],
      instructions: [
        { step: 1, text: 'Toast bread until golden' },
        { step: 2, text: 'Mash avocado with lemon juice and salt' },
        { step: 3, text: 'Poach eggs in simmering water for 3-4 minutes' },
        { step: 4, text: 'Spread avocado on toast, top with poached egg and chili flakes' },
      ],
    },
    {
      name: 'French Toast',
      description: 'Cinnamon-spiced French toast with powdered sugar and syrup',
      imageUrl: '/images/dishes/french-toast.jpg',
      category: 'breakfast',
      difficulty: 2,
      prepTime: 5,
      cookTime: 10,
      nutrition: { calories: 420, protein: 12, fat: 16, carbs: 58 },
      ingredients: [
        { name: 'bread', amount: '4', unit: 'slices', category: 'grain' },
        { name: 'egg', amount: '3', unit: 'whole', category: 'protein' },
        { name: 'milk', amount: '0.5', unit: 'cup', category: 'dairy' },
        { name: 'cinnamon', amount: '1', unit: 'tsp', category: 'spice' },
        { name: 'vanilla extract', amount: '1', unit: 'tsp', category: 'flavoring' },
        { name: 'butter', amount: '2', unit: 'tbsp', category: 'dairy' },
        { name: 'maple syrup', amount: '3', unit: 'tbsp', category: 'sweetener' },
      ],
      instructions: [
        { step: 1, text: 'Whisk together eggs, milk, cinnamon, and vanilla' },
        { step: 2, text: 'Dip bread slices in egg mixture, coating both sides' },
        { step: 3, text: 'Melt butter in pan over medium heat' },
        { step: 4, text: 'Cook bread until golden brown, about 3 minutes per side' },
        { step: 5, text: 'Serve with maple syrup and powdered sugar' },
      ],
    },
    {
      name: 'Breakfast Burrito',
      description: 'Loaded breakfast burrito with scrambled eggs, bacon, cheese, and salsa',
      imageUrl: '/images/dishes/breakfast-burrito.jpg',
      category: 'breakfast',
      difficulty: 3,
      prepTime: 10,
      cookTime: 15,
      nutrition: { calories: 520, protein: 26, fat: 28, carbs: 42 },
      ingredients: [
        { name: 'tortilla', amount: '2', unit: 'large', category: 'grain' },
        { name: 'egg', amount: '4', unit: 'whole', category: 'protein' },
        { name: 'bacon', amount: '4', unit: 'strips', category: 'protein' },
        { name: 'cheese', amount: '0.5', unit: 'cup', category: 'dairy' },
        { name: 'onion', amount: '0.25', unit: 'cup', category: 'vegetable' },
        { name: 'bell pepper', amount: '0.25', unit: 'cup', category: 'vegetable' },
        { name: 'salsa', amount: '0.25', unit: 'cup', category: 'condiment' },
      ],
      instructions: [
        { step: 1, text: 'Cook bacon until crispy, then chop' },
        { step: 2, text: 'Scramble eggs with salt and pepper' },
        { step: 3, text: 'Sauté onions and peppers' },
        { step: 4, text: 'Warm tortillas' },
        { step: 5, text: 'Fill tortillas with eggs, bacon, vegetables, and cheese' },
        { step: 6, text: 'Roll tightly and serve with salsa' },
      ],
    },
    {
      name: 'Granola Parfait',
      description: 'Layered yogurt parfait with homemade granola and fresh berries',
      imageUrl: '/images/dishes/granola-parfait.jpg',
      category: 'breakfast',
      difficulty: 1,
      prepTime: 5,
      cookTime: 0,
      nutrition: { calories: 340, protein: 14, fat: 10, carbs: 52 },
      ingredients: [
        { name: 'greek yogurt', amount: '1.5', unit: 'cups', category: 'dairy' },
        { name: 'granola', amount: '0.5', unit: 'cup', category: 'grain' },
        { name: 'strawberries', amount: '0.5', unit: 'cup', category: 'fruit' },
        { name: 'blueberries', amount: '0.25', unit: 'cup', category: 'fruit' },
        { name: 'honey', amount: '2', unit: 'tbsp', category: 'sweetener' },
      ],
      instructions: [
        { step: 1, text: 'Layer yogurt in glass' },
        { step: 2, text: 'Add granola layer' },
        { step: 3, text: 'Add fresh berries' },
        { step: 4, text: 'Repeat layers' },
        { step: 5, text: 'Drizzle with honey' },
      ],
    },
    {
      name: 'Shakshuka',
      description: 'Middle Eastern poached eggs in spicy tomato sauce with herbs',
      imageUrl: '/images/dishes/shakshuka.jpg',
      category: 'breakfast',
      difficulty: 3,
      prepTime: 10,
      cookTime: 25,
      nutrition: { calories: 280, protein: 16, fat: 18, carbs: 16 },
      ingredients: [
        { name: 'egg', amount: '4', unit: 'whole', category: 'protein' },
        { name: 'tomato', amount: '4', unit: 'medium', category: 'vegetable' },
        { name: 'onion', amount: '1', unit: 'medium', category: 'vegetable' },
        { name: 'bell pepper', amount: '1', unit: 'whole', category: 'vegetable' },
        { name: 'garlic', amount: '3', unit: 'cloves', category: 'aromatic' },
        { name: 'cumin', amount: '1', unit: 'tsp', category: 'spice' },
        { name: 'paprika', amount: '1', unit: 'tsp', category: 'spice' },
        { name: 'olive oil', amount: '2', unit: 'tbsp', category: 'fat' },
        { name: 'parsley', amount: '0.25', unit: 'cup', category: 'herb' },
      ],
      instructions: [
        { step: 1, text: 'Sauté onions and peppers in olive oil until soft' },
        { step: 2, text: 'Add garlic, cumin, and paprika, cook 1 minute' },
        { step: 3, text: 'Add crushed tomatoes and simmer 15 minutes' },
        { step: 4, text: 'Make wells in sauce and crack eggs into them' },
        { step: 5, text: 'Cover and cook until eggs are set, about 8 minutes' },
        { step: 6, text: 'Garnish with parsley and serve with bread' },
      ],
    },
    {
      name: 'Eggs Benedict',
      description: 'Poached eggs on English muffins with Canadian bacon and hollandaise',
      imageUrl: '/images/dishes/eggs-benedict.jpg',
      category: 'breakfast',
      difficulty: 4,
      prepTime: 15,
      cookTime: 20,
      nutrition: { calories: 580, protein: 24, fat: 42, carbs: 28 },
      ingredients: [
        { name: 'english muffin', amount: '2', unit: 'whole', category: 'grain' },
        { name: 'egg', amount: '4', unit: 'whole', category: 'protein' },
        { name: 'canadian bacon', amount: '4', unit: 'slices', category: 'protein' },
        { name: 'butter', amount: '0.5', unit: 'cup', category: 'dairy' },
        { name: 'egg yolk', amount: '3', unit: 'whole', category: 'protein' },
        { name: 'lemon', amount: '1', unit: 'whole', category: 'fruit' },
        { name: 'cayenne pepper', amount: '0.125', unit: 'tsp', category: 'spice' },
      ],
      instructions: [
        { step: 1, text: 'Make hollandaise: blend egg yolks with lemon juice, slowly add melted butter' },
        { step: 2, text: 'Toast English muffins' },
        { step: 3, text: 'Poach eggs in simmering water' },
        { step: 4, text: 'Warm Canadian bacon in pan' },
        { step: 5, text: 'Assemble: muffin, bacon, poached egg, hollandaise sauce' },
        { step: 6, text: 'Garnish with cayenne pepper' },
      ],
    },
    {
      name: 'Breakfast Quinoa Bowl',
      description: 'Warm quinoa bowl with almond milk, cinnamon, fruits, and nuts',
      imageUrl: '/images/dishes/quinoa-bowl.jpg',
      category: 'breakfast',
      difficulty: 2,
      prepTime: 5,
      cookTime: 20,
      nutrition: { calories: 380, protein: 12, fat: 14, carbs: 54 },
      ingredients: [
        { name: 'quinoa', amount: '0.5', unit: 'cup', category: 'grain' },
        { name: 'almond milk', amount: '1', unit: 'cup', category: 'dairy' },
        { name: 'cinnamon', amount: '0.5', unit: 'tsp', category: 'spice' },
        { name: 'banana', amount: '1', unit: 'whole', category: 'fruit' },
        { name: 'almonds', amount: '0.25', unit: 'cup', category: 'nut' },
        { name: 'maple syrup', amount: '2', unit: 'tbsp', category: 'sweetener' },
        { name: 'berries', amount: '0.5', unit: 'cup', category: 'fruit' },
      ],
      instructions: [
        { step: 1, text: 'Cook quinoa in almond milk with cinnamon' },
        { step: 2, text: 'When quinoa is tender and liquid absorbed, remove from heat' },
        { step: 3, text: 'Top with sliced banana, berries, and almonds' },
        { step: 4, text: 'Drizzle with maple syrup' },
      ],
    },
    // LUNCH (12 dishes)
    {
      name: 'Caesar Salad',
      description: 'Classic Caesar salad with crispy romaine, parmesan, and homemade dressing',
      imageUrl: '/images/dishes/caesar-salad.jpg',
      category: 'lunch',
      difficulty: 2,
      prepTime: 15,
      cookTime: 0,
      nutrition: { calories: 320, protein: 12, fat: 24, carbs: 18 },
      ingredients: [
        { name: 'romaine lettuce', amount: '1', unit: 'head', category: 'vegetable' },
        { name: 'parmesan cheese', amount: '0.5', unit: 'cup', category: 'dairy' },
        { name: 'croutons', amount: '1', unit: 'cup', category: 'grain' },
        { name: 'garlic', amount: '2', unit: 'cloves', category: 'aromatic' },
        { name: 'anchovy', amount: '4', unit: 'fillets', category: 'protein' },
        { name: 'lemon', amount: '1', unit: 'whole', category: 'fruit' },
        { name: 'olive oil', amount: '0.5', unit: 'cup', category: 'fat' },
        { name: 'egg yolk', amount: '1', unit: 'whole', category: 'protein' },
      ],
      instructions: [
        { step: 1, text: 'Make dressing: blend garlic, anchovies, lemon juice, egg yolk' },
        { step: 2, text: 'Slowly drizzle in olive oil while blending' },
        { step: 3, text: 'Chop romaine and place in large bowl' },
        { step: 4, text: 'Toss with dressing' },
        { step: 5, text: 'Add croutons and shaved parmesan' },
      ],
    },
    {
      name: 'Grilled Chicken Sandwich',
      description: 'Juicy grilled chicken breast with lettuce, tomato, and avocado on ciabatta',
      imageUrl: '/images/dishes/chicken-sandwich.jpg',
      category: 'lunch',
      difficulty: 2,
      prepTime: 10,
      cookTime: 15,
      nutrition: { calories: 480, protein: 36, fat: 18, carbs: 42 },
      ingredients: [
        { name: 'chicken breast', amount: '1', unit: 'whole', category: 'protein' },
        { name: 'ciabatta bread', amount: '1', unit: 'roll', category: 'grain' },
        { name: 'lettuce', amount: '2', unit: 'leaves', category: 'vegetable' },
        { name: 'tomato', amount: '2', unit: 'slices', category: 'vegetable' },
        { name: 'avocado', amount: '0.5', unit: 'whole', category: 'vegetable' },
        { name: 'mayonnaise', amount: '2', unit: 'tbsp', category: 'condiment' },
        { name: 'olive oil', amount: '1', unit: 'tbsp', category: 'fat' },
      ],
      instructions: [
        { step: 1, text: 'Season chicken with salt and pepper' },
        { step: 2, text: 'Grill chicken 6-7 minutes per side until cooked through' },
        { step: 3, text: 'Toast ciabatta bread' },
        { step: 4, text: 'Spread mayo on bread' },
        { step: 5, text: 'Layer lettuce, tomato, chicken, and sliced avocado' },
        { step: 6, text: 'Top with other half of bread' },
      ],
    },
    {
      name: 'Tomato Soup',
      description: 'Creamy roasted tomato soup with fresh basil and grilled cheese croutons',
      imageUrl: '/images/dishes/tomato-soup.jpg',
      category: 'lunch',
      difficulty: 2,
      prepTime: 10,
      cookTime: 35,
      nutrition: { calories: 280, protein: 8, fat: 16, carbs: 28 },
      ingredients: [
        { name: 'tomato', amount: '2', unit: 'lbs', category: 'vegetable' },
        { name: 'onion', amount: '1', unit: 'medium', category: 'vegetable' },
        { name: 'garlic', amount: '4', unit: 'cloves', category: 'aromatic' },
        { name: 'cream', amount: '0.5', unit: 'cup', category: 'dairy' },
        { name: 'vegetable broth', amount: '2', unit: 'cups', category: 'liquid' },
        { name: 'basil', amount: '0.25', unit: 'cup', category: 'herb' },
        { name: 'olive oil', amount: '3', unit: 'tbsp', category: 'fat' },
      ],
      instructions: [
        { step: 1, text: 'Roast tomatoes, onion, and garlic with olive oil at 400°F for 25 minutes' },
        { step: 2, text: 'Transfer to pot, add broth and basil' },
        { step: 3, text: 'Simmer 10 minutes' },
        { step: 4, text: 'Blend until smooth' },
        { step: 5, text: 'Stir in cream and season with salt and pepper' },
      ],
    },
    {
      name: 'Buddha Bowl',
      description: 'Colorful grain bowl with roasted vegetables, chickpeas, and tahini dressing',
      imageUrl: '/images/dishes/buddha-bowl.jpg',
      category: 'lunch',
      difficulty: 2,
      prepTime: 15,
      cookTime: 30,
      nutrition: { calories: 420, protein: 16, fat: 18, carbs: 54 },
      ingredients: [
        { name: 'quinoa', amount: '0.75', unit: 'cup', category: 'grain' },
        { name: 'chickpeas', amount: '1', unit: 'cup', category: 'protein' },
        { name: 'sweet potato', amount: '1', unit: 'medium', category: 'vegetable' },
        { name: 'kale', amount: '2', unit: 'cups', category: 'vegetable' },
        { name: 'avocado', amount: '0.5', unit: 'whole', category: 'vegetable' },
        { name: 'tahini', amount: '3', unit: 'tbsp', category: 'condiment' },
        { name: 'lemon', amount: '1', unit: 'whole', category: 'fruit' },
      ],
      instructions: [
        { step: 1, text: 'Cook quinoa according to package directions' },
        { step: 2, text: 'Roast sweet potato cubes and chickpeas at 400°F for 25 minutes' },
        { step: 3, text: 'Massage kale with olive oil' },
        { step: 4, text: 'Make tahini dressing: mix tahini, lemon juice, water, salt' },
        { step: 5, text: 'Arrange quinoa, vegetables, and chickpeas in bowl' },
        { step: 6, text: 'Top with sliced avocado and drizzle with tahini dressing' },
      ],
    },
    {
      name: 'Chicken Wrap',
      description: 'Whole wheat wrap filled with grilled chicken, hummus, and fresh veggies',
      imageUrl: '/images/dishes/chicken-wrap.jpg',
      category: 'lunch',
      difficulty: 1,
      prepTime: 10,
      cookTime: 10,
      nutrition: { calories: 380, protein: 28, fat: 14, carbs: 38 },
      ingredients: [
        { name: 'whole wheat tortilla', amount: '1', unit: 'large', category: 'grain' },
        { name: 'chicken breast', amount: '4', unit: 'oz', category: 'protein' },
        { name: 'hummus', amount: '3', unit: 'tbsp', category: 'condiment' },
        { name: 'lettuce', amount: '1', unit: 'cup', category: 'vegetable' },
        { name: 'tomato', amount: '0.5', unit: 'cup', category: 'vegetable' },
        { name: 'cucumber', amount: '0.25', unit: 'cup', category: 'vegetable' },
        { name: 'red onion', amount: '2', unit: 'tbsp', category: 'vegetable' },
      ],
      instructions: [
        { step: 1, text: 'Grill or pan-fry chicken, then slice' },
        { step: 2, text: 'Warm tortilla slightly' },
        { step: 3, text: 'Spread hummus on tortilla' },
        { step: 4, text: 'Layer lettuce, chicken, tomato, cucumber, and onion' },
        { step: 5, text: 'Roll tightly, tucking in sides' },
        { step: 6, text: 'Cut in half diagonally' },
      ],
    },
    {
      name: 'Mediterranean Quinoa Salad',
      description: 'Light quinoa salad with cucumber, feta, olives, and lemon dressing',
      imageUrl: '/images/dishes/quinoa-salad.jpg',
      category: 'lunch',
      difficulty: 1,
      prepTime: 15,
      cookTime: 15,
      nutrition: { calories: 340, protein: 12, fat: 16, carbs: 42 },
      ingredients: [
        { name: 'quinoa', amount: '1', unit: 'cup', category: 'grain' },
        { name: 'cucumber', amount: '1', unit: 'medium', category: 'vegetable' },
        { name: 'cherry tomatoes', amount: '1', unit: 'cup', category: 'vegetable' },
        { name: 'feta cheese', amount: '0.5', unit: 'cup', category: 'dairy' },
        { name: 'kalamata olives', amount: '0.25', unit: 'cup', category: 'vegetable' },
        { name: 'red onion', amount: '0.25', unit: 'cup', category: 'vegetable' },
        { name: 'lemon', amount: '1', unit: 'whole', category: 'fruit' },
        { name: 'olive oil', amount: '3', unit: 'tbsp', category: 'fat' },
      ],
      instructions: [
        { step: 1, text: 'Cook quinoa and let cool' },
        { step: 2, text: 'Dice cucumber, halve tomatoes, chop olives and onion' },
        { step: 3, text: 'Mix lemon juice and olive oil for dressing' },
        { step: 4, text: 'Combine all ingredients in large bowl' },
        { step: 5, text: 'Toss with dressing and crumbled feta' },
      ],
    },
    {
      name: 'Poke Bowl',
      description: 'Hawaiian-style ahi tuna poke bowl with rice, edamame, and spicy mayo',
      imageUrl: '/images/dishes/poke-bowl.jpg',
      category: 'lunch',
      difficulty: 2,
      prepTime: 20,
      cookTime: 15,
      nutrition: { calories: 480, protein: 32, fat: 16, carbs: 52 },
      ingredients: [
        { name: 'sushi rice', amount: '1', unit: 'cup', category: 'grain' },
        { name: 'ahi tuna', amount: '8', unit: 'oz', category: 'protein' },
        { name: 'soy sauce', amount: '2', unit: 'tbsp', category: 'condiment' },
        { name: 'sesame oil', amount: '1', unit: 'tsp', category: 'fat' },
        { name: 'edamame', amount: '0.5', unit: 'cup', category: 'protein' },
        { name: 'avocado', amount: '0.5', unit: 'whole', category: 'vegetable' },
        { name: 'cucumber', amount: '0.5', unit: 'cup', category: 'vegetable' },
        { name: 'seaweed', amount: '2', unit: 'tbsp', category: 'vegetable' },
      ],
      instructions: [
        { step: 1, text: 'Cook sushi rice according to package directions' },
        { step: 2, text: 'Dice tuna into cubes and marinate in soy sauce and sesame oil' },
        { step: 3, text: 'Prepare vegetables: slice cucumber, dice avocado' },
        { step: 4, text: 'Arrange rice in bowl, top with tuna and vegetables' },
        { step: 5, text: 'Garnish with sesame seeds and seaweed' },
      ],
    },
    {
      name: 'Margherita Pizza',
      description: 'Classic Neapolitan pizza with fresh mozzarella, basil, and tomato sauce',
      imageUrl: '/images/dishes/margherita-pizza.jpg',
      category: 'lunch',
      difficulty: 3,
      prepTime: 90,
      cookTime: 12,
      nutrition: { calories: 580, protein: 24, fat: 22, carbs: 72 },
      ingredients: [
        { name: 'pizza dough', amount: '1', unit: 'ball', category: 'grain' },
        { name: 'tomato sauce', amount: '0.5', unit: 'cup', category: 'condiment' },
        { name: 'fresh mozzarella', amount: '8', unit: 'oz', category: 'dairy' },
        { name: 'fresh basil', amount: '10', unit: 'leaves', category: 'herb' },
        { name: 'olive oil', amount: '2', unit: 'tbsp', category: 'fat' },
        { name: 'garlic', amount: '2', unit: 'cloves', category: 'aromatic' },
      ],
      instructions: [
        { step: 1, text: 'Preheat oven to 500°F with pizza stone' },
        { step: 2, text: 'Stretch dough into 12-inch circle' },
        { step: 3, text: 'Spread tomato sauce, leaving 1-inch border' },
        { step: 4, text: 'Top with torn mozzarella' },
        { step: 5, text: 'Bake 10-12 minutes until crust is golden' },
        { step: 6, text: 'Top with fresh basil and drizzle with olive oil' },
      ],
    },
    {
      name: 'Caprese Sandwich',
      description: 'Italian sandwich with fresh mozzarella, tomatoes, basil, and balsamic glaze',
      imageUrl: '/images/dishes/caprese-sandwich.jpg',
      category: 'lunch',
      difficulty: 1,
      prepTime: 10,
      cookTime: 0,
      nutrition: { calories: 420, protein: 18, fat: 22, carbs: 38 },
      ingredients: [
        { name: 'ciabatta bread', amount: '1', unit: 'roll', category: 'grain' },
        { name: 'fresh mozzarella', amount: '4', unit: 'oz', category: 'dairy' },
        { name: 'tomato', amount: '1', unit: 'large', category: 'vegetable' },
        { name: 'fresh basil', amount: '6', unit: 'leaves', category: 'herb' },
        { name: 'balsamic vinegar', amount: '2', unit: 'tbsp', category: 'condiment' },
        { name: 'olive oil', amount: '1', unit: 'tbsp', category: 'fat' },
      ],
      instructions: [
        { step: 1, text: 'Slice ciabatta horizontally' },
        { step: 2, text: 'Drizzle inside with olive oil' },
        { step: 3, text: 'Layer sliced mozzarella, tomato, and basil' },
        { step: 4, text: 'Drizzle with balsamic vinegar' },
        { step: 5, text: 'Season with salt and pepper' },
        { step: 6, text: 'Close sandwich and press lightly' },
      ],
    },
    {
      name: 'Greek Salad',
      description: 'Traditional Greek salad with tomatoes, cucumber, feta, and olives',
      imageUrl: '/images/dishes/greek-salad.jpg',
      category: 'lunch',
      difficulty: 1,
      prepTime: 15,
      cookTime: 0,
      nutrition: { calories: 280, protein: 10, fat: 20, carbs: 18 },
      ingredients: [
        { name: 'cucumber', amount: '1', unit: 'large', category: 'vegetable' },
        { name: 'tomato', amount: '3', unit: 'medium', category: 'vegetable' },
        { name: 'red onion', amount: '0.5', unit: 'medium', category: 'vegetable' },
        { name: 'bell pepper', amount: '1', unit: 'whole', category: 'vegetable' },
        { name: 'feta cheese', amount: '0.75', unit: 'cup', category: 'dairy' },
        { name: 'kalamata olives', amount: '0.5', unit: 'cup', category: 'vegetable' },
        { name: 'olive oil', amount: '0.25', unit: 'cup', category: 'fat' },
        { name: 'lemon', amount: '1', unit: 'whole', category: 'fruit' },
        { name: 'oregano', amount: '1', unit: 'tsp', category: 'herb' },
      ],
      instructions: [
        { step: 1, text: 'Chop cucumber, tomatoes, onion, and pepper into chunks' },
        { step: 2, text: 'Combine vegetables in large bowl' },
        { step: 3, text: 'Add olives' },
        { step: 4, text: 'Whisk together olive oil, lemon juice, and oregano' },
        { step: 5, text: 'Pour dressing over salad and toss' },
        { step: 6, text: 'Top with crumbled feta' },
      ],
    },
    {
      name: 'Tuna Melt',
      description: 'Classic tuna salad sandwich with melted cheese on toasted sourdough',
      imageUrl: '/images/dishes/tuna-melt.jpg',
      category: 'lunch',
      difficulty: 1,
      prepTime: 10,
      cookTime: 5,
      nutrition: { calories: 450, protein: 28, fat: 22, carbs: 36 },
      ingredients: [
        { name: 'canned tuna', amount: '5', unit: 'oz', category: 'protein' },
        { name: 'sourdough bread', amount: '2', unit: 'slices', category: 'grain' },
        { name: 'cheddar cheese', amount: '2', unit: 'slices', category: 'dairy' },
        { name: 'mayonnaise', amount: '3', unit: 'tbsp', category: 'condiment' },
        { name: 'celery', amount: '0.25', unit: 'cup', category: 'vegetable' },
        { name: 'red onion', amount: '2', unit: 'tbsp', category: 'vegetable' },
        { name: 'butter', amount: '1', unit: 'tbsp', category: 'dairy' },
      ],
      instructions: [
        { step: 1, text: 'Mix tuna, mayo, chopped celery, and onion' },
        { step: 2, text: 'Butter one side of each bread slice' },
        { step: 3, text: 'Spread tuna mixture on unbuttered side' },
        { step: 4, text: 'Top with cheese slice' },
        { step: 5, text: 'Grill in pan, buttered side down, until golden and cheese melts' },
      ],
    },
    {
      name: 'Falafel Wrap',
      description: 'Crispy falafel in pita with tahini sauce, lettuce, and pickles',
      imageUrl: '/images/dishes/falafel-wrap.jpg',
      category: 'lunch',
      difficulty: 3,
      prepTime: 20,
      cookTime: 15,
      nutrition: { calories: 480, protein: 16, fat: 22, carbs: 58 },
      ingredients: [
        { name: 'chickpeas', amount: '1.5', unit: 'cups', category: 'protein' },
        { name: 'pita bread', amount: '2', unit: 'whole', category: 'grain' },
        { name: 'onion', amount: '0.5', unit: 'medium', category: 'vegetable' },
        { name: 'garlic', amount: '3', unit: 'cloves', category: 'aromatic' },
        { name: 'parsley', amount: '0.5', unit: 'cup', category: 'herb' },
        { name: 'cumin', amount: '1', unit: 'tsp', category: 'spice' },
        { name: 'tahini', amount: '0.25', unit: 'cup', category: 'condiment' },
        { name: 'lettuce', amount: '1', unit: 'cup', category: 'vegetable' },
      ],
      instructions: [
        { step: 1, text: 'Blend chickpeas, onion, garlic, parsley, cumin, and salt' },
        { step: 2, text: 'Form mixture into small balls' },
        { step: 3, text: 'Fry falafel balls until golden brown, about 3 minutes per side' },
        { step: 4, text: 'Make tahini sauce: mix tahini, lemon juice, water, salt' },
        { step: 5, text: 'Warm pita bread' },
        { step: 6, text: 'Fill pita with falafel, lettuce, and drizzle with tahini sauce' },
      ],
    },
    // DINNER (15 dishes)
    {
      name: 'Spaghetti Carbonara',
      description: 'Creamy pasta with pancetta, eggs, parmesan, and black pepper',
      imageUrl: '/images/dishes/carbonara.jpg',
      category: 'dinner',
      difficulty: 3,
      prepTime: 10,
      cookTime: 20,
      nutrition: { calories: 680, protein: 28, fat: 32, carbs: 68 },
      ingredients: [
        { name: 'spaghetti', amount: '1', unit: 'lb', category: 'grain' },
        { name: 'pancetta', amount: '6', unit: 'oz', category: 'protein' },
        { name: 'egg', amount: '4', unit: 'whole', category: 'protein' },
        { name: 'parmesan cheese', amount: '1', unit: 'cup', category: 'dairy' },
        { name: 'garlic', amount: '3', unit: 'cloves', category: 'aromatic' },
        { name: 'black pepper', amount: '1', unit: 'tsp', category: 'spice' },
        { name: 'olive oil', amount: '2', unit: 'tbsp', category: 'fat' },
      ],
      instructions: [
        { step: 1, text: 'Cook spaghetti according to package, reserve 1 cup pasta water' },
        { step: 2, text: 'Cook pancetta until crispy' },
        { step: 3, text: 'Whisk eggs and parmesan together' },
        { step: 4, text: 'Toss hot pasta with pancetta' },
        { step: 5, text: 'Remove from heat, add egg mixture, toss quickly' },
        { step: 6, text: 'Add pasta water to create creamy sauce, season with pepper' },
      ],
    },
    {
      name: 'Grilled Salmon',
      description: 'Pan-seared salmon with lemon butter sauce and roasted asparagus',
      imageUrl: '/images/dishes/grilled-salmon.jpg',
      category: 'dinner',
      difficulty: 2,
      prepTime: 10,
      cookTime: 20,
      nutrition: { calories: 420, protein: 36, fat: 26, carbs: 12 },
      ingredients: [
        { name: 'salmon fillet', amount: '6', unit: 'oz', category: 'protein' },
        { name: 'asparagus', amount: '8', unit: 'spears', category: 'vegetable' },
        { name: 'lemon', amount: '1', unit: 'whole', category: 'fruit' },
        { name: 'butter', amount: '3', unit: 'tbsp', category: 'dairy' },
        { name: 'garlic', amount: '2', unit: 'cloves', category: 'aromatic' },
        { name: 'olive oil', amount: '2', unit: 'tbsp', category: 'fat' },
        { name: 'dill', amount: '2', unit: 'tbsp', category: 'herb' },
      ],
      instructions: [
        { step: 1, text: 'Season salmon with salt and pepper' },
        { step: 2, text: 'Sear salmon skin-side down in hot pan, 4 minutes' },
        { step: 3, text: 'Flip and cook 3 more minutes' },
        { step: 4, text: 'Roast asparagus with olive oil at 400°F for 15 minutes' },
        { step: 5, text: 'Make lemon butter sauce: melt butter, add lemon juice, garlic, dill' },
        { step: 6, text: 'Serve salmon with asparagus and drizzle with sauce' },
      ],
    },
    {
      name: 'Chicken Stir-Fry',
      description: 'Quick Asian stir-fry with chicken, vegetables, and savory sauce',
      imageUrl: '/images/dishes/chicken-stir-fry.jpg',
      category: 'dinner',
      difficulty: 2,
      prepTime: 15,
      cookTime: 15,
      nutrition: { calories: 450, protein: 32, fat: 16, carbs: 48 },
      ingredients: [
        { name: 'chicken breast', amount: '1', unit: 'lb', category: 'protein' },
        { name: 'broccoli', amount: '2', unit: 'cups', category: 'vegetable' },
        { name: 'bell pepper', amount: '1', unit: 'whole', category: 'vegetable' },
        { name: 'carrot', amount: '1', unit: 'medium', category: 'vegetable' },
        { name: 'soy sauce', amount: '3', unit: 'tbsp', category: 'condiment' },
        { name: 'ginger', amount: '1', unit: 'tbsp', category: 'aromatic' },
        { name: 'garlic', amount: '3', unit: 'cloves', category: 'aromatic' },
        { name: 'rice', amount: '1', unit: 'cup', category: 'grain' },
      ],
      instructions: [
        { step: 1, text: 'Cook rice according to package' },
        { step: 2, text: 'Cut chicken into bite-sized pieces' },
        { step: 3, text: 'Stir-fry chicken in hot wok with oil until cooked' },
        { step: 4, text: 'Add vegetables and stir-fry 3-4 minutes' },
        { step: 5, text: 'Add soy sauce, ginger, and garlic' },
        { step: 6, text: 'Serve over rice' },
      ],
    },
    {
      name: 'Beef Tacos',
      description: 'Seasoned ground beef tacos with all the toppings',
      imageUrl: '/images/dishes/beef-tacos.jpg',
      category: 'dinner',
      difficulty: 2,
      prepTime: 10,
      cookTime: 15,
      nutrition: { calories: 520, protein: 28, fat: 26, carbs: 44 },
      ingredients: [
        { name: 'ground beef', amount: '1', unit: 'lb', category: 'protein' },
        { name: 'taco shells', amount: '8', unit: 'shells', category: 'grain' },
        { name: 'lettuce', amount: '1', unit: 'cup', category: 'vegetable' },
        { name: 'tomato', amount: '1', unit: 'cup', category: 'vegetable' },
        { name: 'cheese', amount: '1', unit: 'cup', category: 'dairy' },
        { name: 'sour cream', amount: '0.5', unit: 'cup', category: 'dairy' },
        { name: 'onion', amount: '0.5', unit: 'medium', category: 'vegetable' },
        { name: 'taco seasoning', amount: '2', unit: 'tbsp', category: 'spice' },
      ],
      instructions: [
        { step: 1, text: 'Brown ground beef in pan' },
        { step: 2, text: 'Add taco seasoning and water, simmer 5 minutes' },
        { step: 3, text: 'Warm taco shells' },
        { step: 4, text: 'Chop lettuce, tomato, and onion' },
        { step: 5, text: 'Fill shells with beef' },
        { step: 6, text: 'Top with lettuce, tomato, cheese, and sour cream' },
      ],
    },
    {
      name: 'Pad Thai',
      description: 'Classic Thai rice noodles with shrimp, peanuts, and tamarind sauce',
      imageUrl: '/images/dishes/pad-thai.jpg',
      category: 'dinner',
      difficulty: 3,
      prepTime: 20,
      cookTime: 15,
      nutrition: { calories: 540, protein: 24, fat: 18, carbs: 72 },
      ingredients: [
        { name: 'rice noodles', amount: '8', unit: 'oz', category: 'grain' },
        { name: 'shrimp', amount: '8', unit: 'oz', category: 'protein' },
        { name: 'egg', amount: '2', unit: 'whole', category: 'protein' },
        { name: 'bean sprouts', amount: '1', unit: 'cup', category: 'vegetable' },
        { name: 'scallion', amount: '3', unit: 'stalks', category: 'vegetable' },
        { name: 'peanuts', amount: '0.25', unit: 'cup', category: 'nut' },
        { name: 'tamarind paste', amount: '2', unit: 'tbsp', category: 'condiment' },
        { name: 'fish sauce', amount: '2', unit: 'tbsp', category: 'condiment' },
        { name: 'lime', amount: '1', unit: 'whole', category: 'fruit' },
      ],
      instructions: [
        { step: 1, text: 'Soak rice noodles in hot water until soft' },
        { step: 2, text: 'Make sauce: mix tamarind paste, fish sauce, sugar' },
        { step: 3, text: 'Stir-fry shrimp until pink, remove' },
        { step: 4, text: 'Scramble eggs in same pan' },
        { step: 5, text: 'Add noodles, sauce, and shrimp back to pan' },
        { step: 6, text: 'Toss with bean sprouts, serve with peanuts, scallions, and lime' },
      ],
    },
    {
      name: 'Chicken Tikka Masala',
      description: 'Creamy Indian curry with marinated chicken in tomato-based sauce',
      imageUrl: '/images/dishes/tikka-masala.jpg',
      category: 'dinner',
      difficulty: 3,
      prepTime: 30,
      cookTime: 30,
      nutrition: { calories: 580, protein: 36, fat: 28, carbs: 48 },
      ingredients: [
        { name: 'chicken breast', amount: '1.5', unit: 'lbs', category: 'protein' },
        { name: 'yogurt', amount: '1', unit: 'cup', category: 'dairy' },
        { name: 'tomato sauce', amount: '2', unit: 'cups', category: 'condiment' },
        { name: 'cream', amount: '0.5', unit: 'cup', category: 'dairy' },
        { name: 'onion', amount: '1', unit: 'large', category: 'vegetable' },
        { name: 'garlic', amount: '4', unit: 'cloves', category: 'aromatic' },
        { name: 'ginger', amount: '1', unit: 'tbsp', category: 'aromatic' },
        { name: 'garam masala', amount: '2', unit: 'tsp', category: 'spice' },
        { name: 'rice', amount: '1', unit: 'cup', category: 'grain' },
      ],
      instructions: [
        { step: 1, text: 'Marinate chicken in yogurt and spices for 30 minutes' },
        { step: 2, text: 'Grill or broil chicken until charred' },
        { step: 3, text: 'Sauté onions, garlic, and ginger' },
        { step: 4, text: 'Add tomato sauce and garam masala, simmer' },
        { step: 5, text: 'Add cream and grilled chicken pieces' },
        { step: 6, text: 'Serve over basmati rice' },
      ],
    },
    {
      name: 'Lasagna',
      description: 'Classic Italian lasagna with meat sauce, ricotta, and mozzarella',
      imageUrl: '/images/dishes/lasagna.jpg',
      category: 'dinner',
      difficulty: 4,
      prepTime: 30,
      cookTime: 60,
      nutrition: { calories: 680, protein: 38, fat: 32, carbs: 58 },
      ingredients: [
        { name: 'lasagna noodles', amount: '12', unit: 'sheets', category: 'grain' },
        { name: 'ground beef', amount: '1', unit: 'lb', category: 'protein' },
        { name: 'ricotta cheese', amount: '2', unit: 'cups', category: 'dairy' },
        { name: 'mozzarella cheese', amount: '3', unit: 'cups', category: 'dairy' },
        { name: 'parmesan cheese', amount: '1', unit: 'cup', category: 'dairy' },
        { name: 'tomato sauce', amount: '4', unit: 'cups', category: 'condiment' },
        { name: 'onion', amount: '1', unit: 'medium', category: 'vegetable' },
        { name: 'garlic', amount: '4', unit: 'cloves', category: 'aromatic' },
      ],
      instructions: [
        { step: 1, text: 'Cook lasagna noodles according to package' },
        { step: 2, text: 'Brown beef with onions and garlic' },
        { step: 3, text: 'Add tomato sauce to beef, simmer 20 minutes' },
        { step: 4, text: 'Mix ricotta with 1 cup mozzarella and 0.5 cup parmesan' },
        { step: 5, text: 'Layer: sauce, noodles, ricotta mixture, repeat' },
        { step: 6, text: 'Top with remaining mozzarella and bake at 375°F for 45 minutes' },
      ],
    },
    {
      name: 'Teriyaki Chicken',
      description: 'Glazed chicken thighs with homemade teriyaki sauce over rice',
      imageUrl: '/images/dishes/teriyaki-chicken.jpg',
      category: 'dinner',
      difficulty: 2,
      prepTime: 10,
      cookTime: 25,
      nutrition: { calories: 520, protein: 34, fat: 18, carbs: 56 },
      ingredients: [
        { name: 'chicken thighs', amount: '1.5', unit: 'lbs', category: 'protein' },
        { name: 'soy sauce', amount: '0.5', unit: 'cup', category: 'condiment' },
        { name: 'mirin', amount: '0.25', unit: 'cup', category: 'condiment' },
        { name: 'sugar', amount: '0.25', unit: 'cup', category: 'sweetener' },
        { name: 'ginger', amount: '1', unit: 'tbsp', category: 'aromatic' },
        { name: 'garlic', amount: '3', unit: 'cloves', category: 'aromatic' },
        { name: 'rice', amount: '1', unit: 'cup', category: 'grain' },
        { name: 'sesame seeds', amount: '1', unit: 'tbsp', category: 'garnish' },
      ],
      instructions: [
        { step: 1, text: 'Cook rice according to package' },
        { step: 2, text: 'Make teriyaki sauce: simmer soy sauce, mirin, sugar until thickened' },
        { step: 3, text: 'Add minced ginger and garlic to sauce' },
        { step: 4, text: 'Pan-fry chicken thighs skin-side down until crispy' },
        { step: 5, text: 'Flip and cook through, then brush with teriyaki sauce' },
        { step: 6, text: 'Serve over rice, sprinkle with sesame seeds' },
      ],
    },
    {
      name: 'Shrimp Scampi',
      description: 'Garlic butter shrimp with white wine sauce over linguine',
      imageUrl: '/images/dishes/shrimp-scampi.jpg',
      category: 'dinner',
      difficulty: 2,
      prepTime: 10,
      cookTime: 15,
      nutrition: { calories: 580, protein: 32, fat: 24, carbs: 58 },
      ingredients: [
        { name: 'linguine', amount: '1', unit: 'lb', category: 'grain' },
        { name: 'shrimp', amount: '1', unit: 'lb', category: 'protein' },
        { name: 'butter', amount: '4', unit: 'tbsp', category: 'dairy' },
        { name: 'garlic', amount: '6', unit: 'cloves', category: 'aromatic' },
        { name: 'white wine', amount: '0.5', unit: 'cup', category: 'liquid' },
        { name: 'lemon', amount: '1', unit: 'whole', category: 'fruit' },
        { name: 'parsley', amount: '0.25', unit: 'cup', category: 'herb' },
        { name: 'red pepper flakes', amount: '0.5', unit: 'tsp', category: 'spice' },
      ],
      instructions: [
        { step: 1, text: 'Cook linguine according to package, reserve pasta water' },
        { step: 2, text: 'Melt butter in large pan' },
        { step: 3, text: 'Sauté garlic and red pepper flakes 1 minute' },
        { step: 4, text: 'Add shrimp, cook until pink' },
        { step: 5, text: 'Add wine and lemon juice, simmer 2 minutes' },
        { step: 6, text: 'Toss with pasta, add pasta water to create sauce, garnish with parsley' },
      ],
    },
    {
      name: 'Beef Stew',
      description: 'Hearty slow-cooked beef stew with vegetables and herbs',
      imageUrl: '/images/dishes/beef-stew.jpg',
      category: 'dinner',
      difficulty: 2,
      prepTime: 20,
      cookTime: 120,
      nutrition: { calories: 480, protein: 32, fat: 18, carbs: 48 },
      ingredients: [
        { name: 'beef chuck', amount: '2', unit: 'lbs', category: 'protein' },
        { name: 'potato', amount: '3', unit: 'large', category: 'vegetable' },
        { name: 'carrot', amount: '3', unit: 'large', category: 'vegetable' },
        { name: 'onion', amount: '2', unit: 'medium', category: 'vegetable' },
        { name: 'beef broth', amount: '4', unit: 'cups', category: 'liquid' },
        { name: 'tomato paste', amount: '2', unit: 'tbsp', category: 'condiment' },
        { name: 'thyme', amount: '2', unit: 'sprigs', category: 'herb' },
        { name: 'flour', amount: '0.25', unit: 'cup', category: 'grain' },
      ],
      instructions: [
        { step: 1, text: 'Cut beef into 1-inch cubes, coat with flour' },
        { step: 2, text: 'Brown beef in batches in Dutch oven' },
        { step: 3, text: 'Add onions, cook until soft' },
        { step: 4, text: 'Add broth, tomato paste, and thyme' },
        { step: 5, text: 'Simmer covered 1.5 hours' },
        { step: 6, text: 'Add chopped potatoes and carrots, cook 30 more minutes' },
      ],
    },
    {
      name: 'Mushroom Risotto',
      description: 'Creamy Arborio rice with wild mushrooms and parmesan',
      imageUrl: '/images/dishes/mushroom-risotto.jpg',
      category: 'dinner',
      difficulty: 3,
      prepTime: 10,
      cookTime: 35,
      nutrition: { calories: 460, protein: 14, fat: 18, carbs: 62 },
      ingredients: [
        { name: 'arborio rice', amount: '1.5', unit: 'cups', category: 'grain' },
        { name: 'mushroom', amount: '12', unit: 'oz', category: 'vegetable' },
        { name: 'vegetable broth', amount: '6', unit: 'cups', category: 'liquid' },
        { name: 'white wine', amount: '0.5', unit: 'cup', category: 'liquid' },
        { name: 'onion', amount: '1', unit: 'small', category: 'vegetable' },
        { name: 'parmesan cheese', amount: '0.75', unit: 'cup', category: 'dairy' },
        { name: 'butter', amount: '3', unit: 'tbsp', category: 'dairy' },
        { name: 'olive oil', amount: '2', unit: 'tbsp', category: 'fat' },
      ],
      instructions: [
        { step: 1, text: 'Keep broth warm in pot' },
        { step: 2, text: 'Sauté mushrooms in butter until golden, set aside' },
        { step: 3, text: 'Sauté diced onion in oil until soft' },
        { step: 4, text: 'Add rice, toast 2 minutes' },
        { step: 5, text: 'Add wine, stir until absorbed' },
        { step: 6, text: 'Add broth one ladle at a time, stirring constantly until absorbed' },
        { step: 7, text: 'When rice is creamy, stir in mushrooms, parmesan, and butter' },
      ],
    },
    {
      name: 'Lamb Curry',
      description: 'Slow-cooked lamb curry with aromatic spices and coconut milk',
      imageUrl: '/images/dishes/lamb-curry.jpg',
      category: 'dinner',
      difficulty: 3,
      prepTime: 20,
      cookTime: 90,
      nutrition: { calories: 620, protein: 38, fat: 36, carbs: 42 },
      ingredients: [
        { name: 'lamb shoulder', amount: '2', unit: 'lbs', category: 'protein' },
        { name: 'coconut milk', amount: '1', unit: 'can', category: 'liquid' },
        { name: 'onion', amount: '2', unit: 'large', category: 'vegetable' },
        { name: 'tomato', amount: '3', unit: 'medium', category: 'vegetable' },
        { name: 'garlic', amount: '6', unit: 'cloves', category: 'aromatic' },
        { name: 'ginger', amount: '2', unit: 'tbsp', category: 'aromatic' },
        { name: 'curry powder', amount: '3', unit: 'tbsp', category: 'spice' },
        { name: 'rice', amount: '1', unit: 'cup', category: 'grain' },
      ],
      instructions: [
        { step: 1, text: 'Cut lamb into chunks, brown in oil' },
        { step: 2, text: 'Sauté onions, garlic, and ginger until soft' },
        { step: 3, text: 'Add curry powder, toast 1 minute' },
        { step: 4, text: 'Add tomatoes and coconut milk' },
        { step: 5, text: 'Return lamb to pot, simmer covered 1.5 hours' },
        { step: 6, text: 'Serve over rice with naan bread' },
      ],
    },
    {
      name: 'BBQ Ribs',
      description: 'Fall-off-the-bone baby back ribs with tangy BBQ sauce',
      imageUrl: '/images/dishes/bbq-ribs.jpg',
      category: 'dinner',
      difficulty: 3,
      prepTime: 15,
      cookTime: 180,
      nutrition: { calories: 720, protein: 42, fat: 48, carbs: 32 },
      ingredients: [
        { name: 'baby back ribs', amount: '2', unit: 'racks', category: 'protein' },
        { name: 'bbq sauce', amount: '1.5', unit: 'cups', category: 'condiment' },
        { name: 'brown sugar', amount: '0.25', unit: 'cup', category: 'sweetener' },
        { name: 'paprika', amount: '2', unit: 'tbsp', category: 'spice' },
        { name: 'garlic powder', amount: '1', unit: 'tbsp', category: 'spice' },
        { name: 'onion powder', amount: '1', unit: 'tbsp', category: 'spice' },
        { name: 'cayenne pepper', amount: '0.5', unit: 'tsp', category: 'spice' },
      ],
      instructions: [
        { step: 1, text: 'Mix brown sugar, paprika, garlic powder, onion powder, cayenne for rub' },
        { step: 2, text: 'Coat ribs generously with rub' },
        { step: 3, text: 'Wrap ribs in foil' },
        { step: 4, text: 'Bake at 275°F for 2.5 hours' },
        { step: 5, text: 'Unwrap, brush with BBQ sauce' },
        { step: 6, text: 'Broil or grill 5 minutes until caramelized' },
      ],
    },
    {
      name: 'Roast Chicken',
      description: 'Classic herb-roasted whole chicken with crispy skin',
      imageUrl: '/images/dishes/roast-chicken.jpg',
      category: 'dinner',
      difficulty: 2,
      prepTime: 15,
      cookTime: 75,
      nutrition: { calories: 480, protein: 42, fat: 28, carbs: 8 },
      ingredients: [
        { name: 'whole chicken', amount: '4', unit: 'lbs', category: 'protein' },
        { name: 'lemon', amount: '1', unit: 'whole', category: 'fruit' },
        { name: 'garlic', amount: '1', unit: 'head', category: 'aromatic' },
        { name: 'rosemary', amount: '3', unit: 'sprigs', category: 'herb' },
        { name: 'thyme', amount: '4', unit: 'sprigs', category: 'herb' },
        { name: 'butter', amount: '4', unit: 'tbsp', category: 'dairy' },
        { name: 'olive oil', amount: '2', unit: 'tbsp', category: 'fat' },
      ],
      instructions: [
        { step: 1, text: 'Preheat oven to 425°F' },
        { step: 2, text: 'Pat chicken dry, season inside and out with salt and pepper' },
        { step: 3, text: 'Stuff cavity with lemon halves, garlic, rosemary, and thyme' },
        { step: 4, text: 'Rub butter under skin and olive oil on outside' },
        { step: 5, text: 'Roast 1 hour 15 minutes until internal temp reaches 165°F' },
        { step: 6, text: 'Let rest 15 minutes before carving' },
      ],
    },
    {
      name: 'Vegetable Curry',
      description: 'Colorful mixed vegetable curry in coconut-tomato sauce',
      imageUrl: '/images/dishes/vegetable-curry.jpg',
      category: 'dinner',
      difficulty: 2,
      prepTime: 15,
      cookTime: 30,
      nutrition: { calories: 380, protein: 12, fat: 18, carbs: 48 },
      ingredients: [
        { name: 'cauliflower', amount: '2', unit: 'cups', category: 'vegetable' },
        { name: 'potato', amount: '2', unit: 'medium', category: 'vegetable' },
        { name: 'chickpeas', amount: '1', unit: 'can', category: 'protein' },
        { name: 'coconut milk', amount: '1', unit: 'can', category: 'liquid' },
        { name: 'tomato', amount: '2', unit: 'medium', category: 'vegetable' },
        { name: 'onion', amount: '1', unit: 'large', category: 'vegetable' },
        { name: 'curry powder', amount: '2', unit: 'tbsp', category: 'spice' },
        { name: 'garlic', amount: '4', unit: 'cloves', category: 'aromatic' },
        { name: 'ginger', amount: '1', unit: 'tbsp', category: 'aromatic' },
        { name: 'rice', amount: '1', unit: 'cup', category: 'grain' },
      ],
      instructions: [
        { step: 1, text: 'Cook rice according to package' },
        { step: 2, text: 'Sauté onions, garlic, and ginger until soft' },
        { step: 3, text: 'Add curry powder, toast 1 minute' },
        { step: 4, text: 'Add diced tomatoes, coconut milk, and vegetables' },
        { step: 5, text: 'Simmer 20 minutes until vegetables are tender' },
        { step: 6, text: 'Serve over rice with naan bread' },
      ],
    },
    // SNACKS (8 dishes)
    {
      name: 'Hummus & Veggies',
      description: 'Creamy homemade hummus with fresh cut vegetables',
      imageUrl: '/images/dishes/hummus-veggies.jpg',
      category: 'snack',
      difficulty: 1,
      prepTime: 10,
      cookTime: 0,
      nutrition: { calories: 220, protein: 8, fat: 12, carbs: 24 },
      ingredients: [
        { name: 'chickpeas', amount: '1', unit: 'can', category: 'protein' },
        { name: 'tahini', amount: '0.25', unit: 'cup', category: 'condiment' },
        { name: 'lemon', amount: '1', unit: 'whole', category: 'fruit' },
        { name: 'garlic', amount: '2', unit: 'cloves', category: 'aromatic' },
        { name: 'carrot', amount: '2', unit: 'medium', category: 'vegetable' },
        { name: 'cucumber', amount: '1', unit: 'medium', category: 'vegetable' },
        { name: 'bell pepper', amount: '1', unit: 'whole', category: 'vegetable' },
      ],
      instructions: [
        { step: 1, text: 'Blend chickpeas, tahini, lemon juice, garlic, and olive oil' },
        { step: 2, text: 'Add water to reach desired consistency' },
        { step: 3, text: 'Season with salt and cumin' },
        { step: 4, text: 'Cut vegetables into sticks' },
        { step: 5, text: 'Serve hummus with veggie sticks' },
      ],
    },
    {
      name: 'Guacamole & Chips',
      description: 'Fresh chunky guacamole with crispy tortilla chips',
      imageUrl: '/images/dishes/guacamole-chips.jpg',
      category: 'snack',
      difficulty: 1,
      prepTime: 10,
      cookTime: 0,
      nutrition: { calories: 320, protein: 4, fat: 22, carbs: 28 },
      ingredients: [
        { name: 'avocado', amount: '3', unit: 'whole', category: 'vegetable' },
        { name: 'lime', amount: '1', unit: 'whole', category: 'fruit' },
        { name: 'tomato', amount: '1', unit: 'small', category: 'vegetable' },
        { name: 'onion', amount: '0.25', unit: 'cup', category: 'vegetable' },
        { name: 'cilantro', amount: '0.25', unit: 'cup', category: 'herb' },
        { name: 'tortilla chips', amount: '2', unit: 'cups', category: 'grain' },
      ],
      instructions: [
        { step: 1, text: 'Mash avocados in bowl' },
        { step: 2, text: 'Mix in lime juice, diced tomato, onion, and cilantro' },
        { step: 3, text: 'Season with salt' },
        { step: 4, text: 'Serve immediately with tortilla chips' },
      ],
    },
    {
      name: 'Cheese Platter',
      description: 'Assorted cheeses with crackers, fruits, and nuts',
      imageUrl: '/images/dishes/cheese-platter.jpg',
      category: 'snack',
      difficulty: 1,
      prepTime: 15,
      cookTime: 0,
      nutrition: { calories: 380, protein: 16, fat: 28, carbs: 18 },
      ingredients: [
        { name: 'cheddar cheese', amount: '2', unit: 'oz', category: 'dairy' },
        { name: 'brie cheese', amount: '2', unit: 'oz', category: 'dairy' },
        { name: 'gouda cheese', amount: '2', unit: 'oz', category: 'dairy' },
        { name: 'crackers', amount: '12', unit: 'pieces', category: 'grain' },
        { name: 'grapes', amount: '0.5', unit: 'cup', category: 'fruit' },
        { name: 'almonds', amount: '0.25', unit: 'cup', category: 'nut' },
        { name: 'honey', amount: '2', unit: 'tbsp', category: 'sweetener' },
      ],
      instructions: [
        { step: 1, text: 'Arrange cheeses on board' },
        { step: 2, text: 'Add crackers around cheeses' },
        { step: 3, text: 'Fill spaces with grapes and almonds' },
        { step: 4, text: 'Drizzle honey over brie' },
      ],
    },
    {
      name: 'Energy Balls',
      description: 'No-bake energy bites with oats, dates, and nut butter',
      imageUrl: '/images/dishes/energy-balls.jpg',
      category: 'snack',
      difficulty: 1,
      prepTime: 15,
      cookTime: 0,
      nutrition: { calories: 180, protein: 4, fat: 8, carbs: 24 },
      ingredients: [
        { name: 'oats', amount: '1', unit: 'cup', category: 'grain' },
        { name: 'dates', amount: '10', unit: 'whole', category: 'fruit' },
        { name: 'peanut butter', amount: '0.5', unit: 'cup', category: 'nut' },
        { name: 'honey', amount: '2', unit: 'tbsp', category: 'sweetener' },
        { name: 'chia seeds', amount: '2', unit: 'tbsp', category: 'seed' },
        { name: 'vanilla extract', amount: '1', unit: 'tsp', category: 'flavoring' },
      ],
      instructions: [
        { step: 1, text: 'Blend dates until paste forms' },
        { step: 2, text: 'Mix all ingredients in bowl' },
        { step: 3, text: 'Roll mixture into 1-inch balls' },
        { step: 4, text: 'Refrigerate 30 minutes to firm up' },
      ],
    },
    {
      name: 'Bruschetta',
      description: 'Toasted bread topped with fresh tomato-basil mixture',
      imageUrl: '/images/dishes/bruschetta.jpg',
      category: 'snack',
      difficulty: 1,
      prepTime: 15,
      cookTime: 5,
      nutrition: { calories: 240, protein: 8, fat: 12, carbs: 28 },
      ingredients: [
        { name: 'baguette', amount: '1', unit: 'loaf', category: 'grain' },
        { name: 'tomato', amount: '4', unit: 'medium', category: 'vegetable' },
        { name: 'garlic', amount: '3', unit: 'cloves', category: 'aromatic' },
        { name: 'basil', amount: '0.5', unit: 'cup', category: 'herb' },
        { name: 'olive oil', amount: '3', unit: 'tbsp', category: 'fat' },
        { name: 'balsamic vinegar', amount: '1', unit: 'tbsp', category: 'condiment' },
      ],
      instructions: [
        { step: 1, text: 'Slice baguette diagonally, brush with olive oil' },
        { step: 2, text: 'Toast bread until golden' },
        { step: 3, text: 'Rub toasted bread with cut garlic clove' },
        { step: 4, text: 'Mix diced tomatoes, basil, olive oil, and balsamic vinegar' },
        { step: 5, text: 'Top bread with tomato mixture' },
      ],
    },
    {
      name: 'Spring Rolls',
      description: 'Fresh Vietnamese spring rolls with shrimp and vegetables',
      imageUrl: '/images/dishes/spring-rolls.jpg',
      category: 'snack',
      difficulty: 2,
      prepTime: 25,
      cookTime: 5,
      nutrition: { calories: 180, protein: 12, fat: 4, carbs: 26 },
      ingredients: [
        { name: 'rice paper', amount: '8', unit: 'sheets', category: 'grain' },
        { name: 'shrimp', amount: '12', unit: 'pieces', category: 'protein' },
        { name: 'rice noodles', amount: '2', unit: 'oz', category: 'grain' },
        { name: 'lettuce', amount: '1', unit: 'cup', category: 'vegetable' },
        { name: 'carrot', amount: '1', unit: 'medium', category: 'vegetable' },
        { name: 'mint', amount: '0.25', unit: 'cup', category: 'herb' },
        { name: 'cilantro', amount: '0.25', unit: 'cup', category: 'herb' },
      ],
      instructions: [
        { step: 1, text: 'Cook shrimp and rice noodles, let cool' },
        { step: 2, text: 'Julienne carrot' },
        { step: 3, text: 'Soak rice paper in warm water until soft' },
        { step: 4, text: 'Layer lettuce, noodles, vegetables, shrimp, herbs on rice paper' },
        { step: 5, text: 'Roll tightly, tucking in sides' },
        { step: 6, text: 'Serve with peanut or hoisin dipping sauce' },
      ],
    },
    {
      name: 'Stuffed Mushrooms',
      description: 'Baked mushroom caps filled with garlic herb cream cheese',
      imageUrl: '/images/dishes/stuffed-mushrooms.jpg',
      category: 'snack',
      difficulty: 2,
      prepTime: 15,
      cookTime: 20,
      nutrition: { calories: 160, protein: 8, fat: 12, carbs: 8 },
      ingredients: [
        { name: 'button mushrooms', amount: '12', unit: 'large', category: 'vegetable' },
        { name: 'cream cheese', amount: '4', unit: 'oz', category: 'dairy' },
        { name: 'parmesan cheese', amount: '0.25', unit: 'cup', category: 'dairy' },
        { name: 'garlic', amount: '2', unit: 'cloves', category: 'aromatic' },
        { name: 'parsley', amount: '2', unit: 'tbsp', category: 'herb' },
        { name: 'bread crumbs', amount: '0.25', unit: 'cup', category: 'grain' },
      ],
      instructions: [
        { step: 1, text: 'Remove mushroom stems, chop finely' },
        { step: 2, text: 'Mix cream cheese, parmesan, garlic, parsley, and chopped stems' },
        { step: 3, text: 'Fill mushroom caps with mixture' },
        { step: 4, text: 'Top with bread crumbs' },
        { step: 5, text: 'Bake at 375°F for 20 minutes until golden' },
      ],
    },
    {
      name: 'Caprese Skewers',
      description: 'Tomato, mozzarella, and basil skewers with balsamic glaze',
      imageUrl: '/images/dishes/caprese-skewers.jpg',
      category: 'snack',
      difficulty: 1,
      prepTime: 10,
      cookTime: 0,
      nutrition: { calories: 180, protein: 10, fat: 12, carbs: 8 },
      ingredients: [
        { name: 'cherry tomatoes', amount: '12', unit: 'whole', category: 'vegetable' },
        { name: 'mozzarella balls', amount: '12', unit: 'pieces', category: 'dairy' },
        { name: 'fresh basil', amount: '12', unit: 'leaves', category: 'herb' },
        { name: 'balsamic glaze', amount: '2', unit: 'tbsp', category: 'condiment' },
        { name: 'olive oil', amount: '1', unit: 'tbsp', category: 'fat' },
        { name: 'skewers', amount: '12', unit: 'pieces', category: 'equipment' },
      ],
      instructions: [
        { step: 1, text: 'Thread tomato, basil leaf, and mozzarella on skewer' },
        { step: 2, text: 'Repeat with remaining skewers' },
        { step: 3, text: 'Arrange on platter' },
        { step: 4, text: 'Drizzle with olive oil and balsamic glaze' },
        { step: 5, text: 'Season with salt and pepper' },
      ],
    },
  ];

  for (const dishData of dishes) {
    const { ingredients, instructions, ...dish } = dishData;
    const createdDish = await prisma.dish.create({ data: dish });

    for (const ing of ingredients) {
      await prisma.ingredient.create({
        data: { ...ing, dishId: createdDish.id },
      });
    }

    for (const inst of instructions) {
      await prisma.instruction.create({
        data: { ...inst, dishId: createdDish.id },
      });
    }
  }

  console.log(`✅ Seeded ${dishes.length} dishes`);
  console.log('🎉 Seed completed successfully!');
}

main()
  .catch((e) => {
    console.error('❌ Seed failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
