import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const dishes = [
  // BREAKFAST
  {
    name: 'Classic Avocado Toast',
    description: 'Creamy avocado spread on crispy sourdough with a perfectly poached egg',
    imageUrl: '/images/dishes/avocado-toast.jpg',
    category: 'breakfast',
    difficulty: 2,
    prepTime: 5,
    cookTime: 5,
    instructions: [
      'Toast sourdough bread until golden and crispy',
      'Mash ripe avocado with salt, pepper, and lemon juice',
      'Poach egg in simmering water with vinegar for 3-4 minutes',
      'Spread avocado on toast, top with poached egg',
      'Season with red pepper flakes and fresh herbs',
    ],
    nutrition: { calories: 320, protein: 12, fat: 18, carbs: 28 },
    tags: ['healthy', 'quick', 'vegetarian'],
    ingredients: [
      { name: 'sourdough bread', amount: '2', unit: 'slices' },
      { name: 'avocado', amount: '1', unit: 'whole', substitutes: ['guacamole'] },
      { name: 'egg', amount: '1', unit: 'whole', substitutes: ['tofu scramble'] },
      { name: 'lemon juice', amount: '1', unit: 'tsp', substitutes: ['lime juice'] },
      { name: 'salt', amount: '1', unit: 'pinch', substitutes: ['sea salt'] },
      { name: 'black pepper', amount: '1', unit: 'pinch', substitutes: ['white pepper'] },
      { name: 'red pepper flakes', amount: '1', unit: 'pinch', substitutes: ['chili powder'] },
    ],
  },
  {
    name: 'Blueberry Pancakes',
    description: 'Fluffy buttermilk pancakes loaded with fresh blueberries and maple syrup',
    imageUrl: '/images/dishes/blueberry-pancakes.jpg',
    category: 'breakfast',
    difficulty: 3,
    prepTime: 10,
    cookTime: 15,
    instructions: [
      'Mix dry ingredients: flour, baking powder, sugar, salt',
      'Whisk together buttermilk, egg, and melted butter',
      'Combine wet and dry ingredients until just mixed',
      'Fold in fresh blueberries gently',
      'Cook on griddle until bubbles form, flip and cook until golden',
      'Serve with butter and maple syrup',
    ],
    nutrition: { calories: 450, protein: 10, fat: 12, carbs: 75 },
    tags: ['sweet', 'family-friendly', 'breakfast'],
    ingredients: [
      { name: 'all-purpose flour', amount: '2', unit: 'cups', substitutes: ['whole wheat flour', 'gluten-free flour'] },
      { name: 'baking powder', amount: '2', unit: 'tsp' },
      { name: 'sugar', amount: '2', unit: 'tbsp', substitutes: ['honey', 'maple syrup'] },
      { name: 'salt', amount: '1/2', unit: 'tsp' },
      { name: 'buttermilk', amount: '1.5', unit: 'cups', substitutes: ['milk with vinegar', 'yogurt'] },
      { name: 'egg', amount: '1', unit: 'whole', substitutes: ['flax egg'] },
      { name: 'butter', amount: '3', unit: 'tbsp', substitutes: ['coconut oil', 'vegetable oil'] },
      { name: 'blueberries', amount: '1', unit: 'cup', substitutes: ['strawberries', 'raspberries', 'chocolate chips'] },
    ],
  },
  {
    name: 'Greek Yogurt Parfait',
    description: 'Layered Greek yogurt with granola, honey, and fresh berries',
    imageUrl: '/images/dishes/yogurt-parfait.jpg',
    category: 'breakfast',
    difficulty: 1,
    prepTime: 5,
    cookTime: 0,
    instructions: [
      'Layer Greek yogurt in a glass or bowl',
      'Add a layer of granola',
      'Top with mixed berries',
      'Drizzle with honey',
      'Repeat layers if desired',
      'Garnish with mint leaves',
    ],
    nutrition: { calories: 280, protein: 18, fat: 8, carbs: 38 },
    tags: ['healthy', 'quick', 'no-cook', 'high-protein'],
    ingredients: [
      { name: 'greek yogurt', amount: '1', unit: 'cup', substitutes: ['regular yogurt', 'skyr'] },
      { name: 'granola', amount: '1/2', unit: 'cup', substitutes: ['oats', 'muesli'] },
      { name: 'mixed berries', amount: '1/2', unit: 'cup', substitutes: ['sliced banana', 'mango'] },
      { name: 'honey', amount: '2', unit: 'tbsp', substitutes: ['maple syrup', 'agave'] },
      { name: 'mint leaves', amount: '2', unit: 'leaves', substitutes: ['basil'] },
    ],
  },
  {
    name: 'Breakfast Burrito',
    description: 'Hearty scrambled eggs with cheese, beans, and salsa wrapped in a warm tortilla',
    imageUrl: '/images/dishes/breakfast-burrito.jpg',
    category: 'breakfast',
    difficulty: 2,
    prepTime: 10,
    cookTime: 10,
    instructions: [
      'Scramble eggs with butter in a non-stick pan',
      'Warm tortillas in a dry pan or microwave',
      'Heat black beans with cumin',
      'Layer eggs, beans, cheese, and salsa on tortilla',
      'Add diced avocado if desired',
      'Roll tightly, tucking in the sides',
      'Optional: grill burrito for crispy exterior',
    ],
    nutrition: { calories: 520, protein: 24, fat: 22, carbs: 55 },
    tags: ['filling', 'savory', 'mexican'],
    ingredients: [
      { name: 'eggs', amount: '3', unit: 'whole', substitutes: ['egg whites', 'tofu scramble'] },
      { name: 'flour tortilla', amount: '2', unit: 'large', substitutes: ['whole wheat tortilla', 'corn tortilla'] },
      { name: 'black beans', amount: '1/2', unit: 'cup', substitutes: ['pinto beans', 'refried beans'] },
      { name: 'cheddar cheese', amount: '1/4', unit: 'cup', substitutes: ['monterey jack', 'pepper jack'] },
      { name: 'salsa', amount: '3', unit: 'tbsp', substitutes: ['pico de gallo', 'hot sauce'] },
      { name: 'butter', amount: '1', unit: 'tbsp', substitutes: ['olive oil'] },
      { name: 'avocado', amount: '1/4', unit: 'whole', substitutes: ['guacamole'] },
    ],
  },

  // LUNCH
  {
    name: 'Caesar Salad with Grilled Chicken',
    description: 'Crisp romaine lettuce with creamy Caesar dressing, parmesan, and grilled chicken',
    imageUrl: '/images/dishes/caesar-salad.jpg',
    category: 'lunch',
    difficulty: 2,
    prepTime: 15,
    cookTime: 15,
    instructions: [
      'Season chicken breast with salt, pepper, and olive oil',
      'Grill chicken for 6-7 minutes per side until cooked through',
      'Let chicken rest, then slice',
      'Tear romaine lettuce into bite-sized pieces',
      'Toss lettuce with Caesar dressing',
      'Top with sliced chicken, parmesan, and croutons',
    ],
    nutrition: { calories: 420, protein: 38, fat: 22, carbs: 18 },
    tags: ['salad', 'high-protein', 'classic'],
    ingredients: [
      { name: 'chicken breast', amount: '6', unit: 'oz', substitutes: ['chicken thigh', 'shrimp', 'tofu'] },
      { name: 'romaine lettuce', amount: '4', unit: 'cups', substitutes: ['kale', 'mixed greens'] },
      { name: 'caesar dressing', amount: '3', unit: 'tbsp' },
      { name: 'parmesan cheese', amount: '1/4', unit: 'cup', substitutes: ['pecorino romano'] },
      { name: 'croutons', amount: '1/2', unit: 'cup' },
      { name: 'olive oil', amount: '1', unit: 'tbsp' },
      { name: 'salt', amount: '1', unit: 'pinch' },
      { name: 'black pepper', amount: '1', unit: 'pinch' },
    ],
  },
  {
    name: 'Caprese Sandwich',
    description: 'Fresh mozzarella, tomatoes, and basil with balsamic glaze on ciabatta',
    imageUrl: '/images/dishes/caprese-sandwich.jpg',
    category: 'lunch',
    difficulty: 1,
    prepTime: 10,
    cookTime: 0,
    instructions: [
      'Slice ciabatta bread in half horizontally',
      'Drizzle olive oil on both sides',
      'Layer sliced mozzarella and tomatoes',
      'Add fresh basil leaves',
      'Drizzle with balsamic glaze',
      'Season with salt and pepper',
      'Close sandwich and serve',
    ],
    nutrition: { calories: 380, protein: 18, fat: 16, carbs: 42 },
    tags: ['italian', 'vegetarian', 'no-cook', 'quick'],
    ingredients: [
      { name: 'ciabatta bread', amount: '1', unit: 'roll', substitutes: ['focaccia', 'sourdough'] },
      { name: 'mozzarella', amount: '4', unit: 'oz', substitutes: ['burrata', 'provolone'] },
      { name: 'tomato', amount: '1', unit: 'large', substitutes: ['cherry tomatoes'] },
      { name: 'fresh basil', amount: '6', unit: 'leaves', substitutes: ['arugula'] },
      { name: 'balsamic glaze', amount: '2', unit: 'tbsp', substitutes: ['balsamic vinegar'] },
      { name: 'olive oil', amount: '1', unit: 'tbsp' },
      { name: 'salt', amount: '1', unit: 'pinch' },
      { name: 'black pepper', amount: '1', unit: 'pinch' },
    ],
  },
  {
    name: 'Asian Chicken Noodle Bowl',
    description: 'Tender chicken with rice noodles, vegetables, and savory soy-ginger sauce',
    imageUrl: '/images/dishes/asian-noodle-bowl.jpg',
    category: 'lunch',
    difficulty: 3,
    prepTime: 15,
    cookTime: 20,
    instructions: [
      'Cook rice noodles according to package instructions',
      'Marinate chicken in soy sauce, ginger, and garlic for 10 minutes',
      'Stir-fry chicken until cooked through, set aside',
      'Stir-fry vegetables: carrots, bell pepper, snap peas',
      'Add noodles back to pan with sauce ingredients',
      'Toss everything together',
      'Garnish with sesame seeds and green onions',
    ],
    nutrition: { calories: 480, protein: 32, fat: 12, carbs: 58 },
    tags: ['asian', 'noodles', 'colorful'],
    ingredients: [
      { name: 'chicken breast', amount: '6', unit: 'oz', substitutes: ['chicken thigh', 'shrimp', 'tofu'] },
      { name: 'rice noodles', amount: '4', unit: 'oz', substitutes: ['soba noodles', 'udon'] },
      { name: 'soy sauce', amount: '3', unit: 'tbsp', substitutes: ['tamari', 'coconut aminos'] },
      { name: 'ginger', amount: '1', unit: 'tbsp', substitutes: ['ginger paste'] },
      { name: 'garlic', amount: '2', unit: 'cloves', substitutes: ['garlic powder'] },
      { name: 'carrot', amount: '1', unit: 'medium', substitutes: ['bell pepper'] },
      { name: 'bell pepper', amount: '1', unit: 'whole', substitutes: ['zucchini'] },
      { name: 'snap peas', amount: '1', unit: 'cup', substitutes: ['snow peas', 'broccoli'] },
      { name: 'sesame oil', amount: '1', unit: 'tbsp', substitutes: ['vegetable oil'] },
      { name: 'green onion', amount: '2', unit: 'stalks', substitutes: ['chives'] },
      { name: 'sesame seeds', amount: '1', unit: 'tsp' },
    ],
  },
  {
    name: 'Mediterranean Quinoa Bowl',
    description: 'Protein-packed quinoa with chickpeas, cucumber, tomatoes, feta, and tahini dressing',
    imageUrl: '/images/dishes/quinoa-bowl.jpg',
    category: 'lunch',
    difficulty: 2,
    prepTime: 10,
    cookTime: 20,
    instructions: [
      'Cook quinoa according to package instructions',
      'Drain and rinse chickpeas',
      'Dice cucumber, tomatoes, and red onion',
      'Crumble feta cheese',
      'Make tahini dressing: tahini, lemon juice, garlic, water',
      'Assemble bowl with quinoa base',
      'Top with vegetables, chickpeas, and feta',
      'Drizzle with tahini dressing',
    ],
    nutrition: { calories: 440, protein: 18, fat: 16, carbs: 58 },
    tags: ['healthy', 'mediterranean', 'vegetarian', 'meal-prep'],
    ingredients: [
      { name: 'quinoa', amount: '1', unit: 'cup', substitutes: ['brown rice', 'couscous'] },
      { name: 'chickpeas', amount: '1', unit: 'cup', substitutes: ['white beans', 'lentils'] },
      { name: 'cucumber', amount: '1', unit: 'medium', substitutes: ['zucchini'] },
      { name: 'cherry tomatoes', amount: '1', unit: 'cup', substitutes: ['regular tomato'] },
      { name: 'red onion', amount: '1/4', unit: 'whole', substitutes: ['white onion', 'shallot'] },
      { name: 'feta cheese', amount: '1/4', unit: 'cup', substitutes: ['goat cheese'] },
      { name: 'tahini', amount: '3', unit: 'tbsp', substitutes: ['greek yogurt'] },
      { name: 'lemon juice', amount: '2', unit: 'tbsp', substitutes: ['lime juice'] },
      { name: 'garlic', amount: '1', unit: 'clove', substitutes: ['garlic powder'] },
    ],
  },
  {
    name: 'Classic BLT Sandwich',
    description: 'Crispy bacon, fresh lettuce, and juicy tomatoes on toasted bread with mayo',
    imageUrl: '/images/dishes/blt-sandwich.jpg',
    category: 'lunch',
    difficulty: 2,
    prepTime: 5,
    cookTime: 10,
    instructions: [
      'Cook bacon in a skillet until crispy',
      'Toast bread until golden brown',
      'Spread mayonnaise on both slices',
      'Layer lettuce leaves on bottom slice',
      'Add sliced tomatoes, season with salt and pepper',
      'Top with crispy bacon strips',
      'Close sandwich and slice diagonally',
    ],
    nutrition: { calories: 420, protein: 16, fat: 24, carbs: 36 },
    tags: ['classic', 'sandwich', 'american'],
    ingredients: [
      { name: 'bacon', amount: '4', unit: 'strips', substitutes: ['turkey bacon', 'tempeh bacon'] },
      { name: 'bread', amount: '2', unit: 'slices', substitutes: ['sourdough', 'whole wheat'] },
      { name: 'lettuce', amount: '2', unit: 'leaves', substitutes: ['romaine', 'arugula'] },
      { name: 'tomato', amount: '3', unit: 'slices', substitutes: ['roasted red pepper'] },
      { name: 'mayonnaise', amount: '2', unit: 'tbsp', substitutes: ['aioli', 'avocado'] },
      { name: 'salt', amount: '1', unit: 'pinch' },
      { name: 'black pepper', amount: '1', unit: 'pinch' },
    ],
  },

  // DINNER
  {
    name: 'Spaghetti Carbonara',
    description: 'Classic Roman pasta with crispy pancetta, eggs, and pecorino cheese',
    imageUrl: '/images/dishes/carbonara.jpg',
    category: 'dinner',
    difficulty: 3,
    prepTime: 10,
    cookTime: 20,
    instructions: [
      'Cook spaghetti in salted boiling water until al dente',
      'Crisp pancetta in a large pan',
      'Whisk eggs with grated pecorino and black pepper',
      'Reserve 1 cup pasta water, drain pasta',
      'Remove pan from heat, add hot pasta to pancetta',
      'Quickly stir in egg mixture, adding pasta water to create creamy sauce',
      'Serve immediately with extra cheese and pepper',
    ],
    nutrition: { calories: 620, protein: 28, fat: 28, carbs: 62 },
    tags: ['italian', 'pasta', 'classic', 'comfort-food'],
    ingredients: [
      { name: 'spaghetti', amount: '12', unit: 'oz', substitutes: ['linguine', 'fettuccine'] },
      { name: 'pancetta', amount: '6', unit: 'oz', substitutes: ['bacon', 'guanciale'] },
      { name: 'eggs', amount: '3', unit: 'whole', substitutes: ['egg yolks only'] },
      { name: 'pecorino romano', amount: '1', unit: 'cup', substitutes: ['parmesan'] },
      { name: 'black pepper', amount: '2', unit: 'tsp' },
      { name: 'salt', amount: '1', unit: 'pinch' },
    ],
  },
  {
    name: 'Grilled Salmon with Asparagus',
    description: 'Perfectly grilled salmon fillet with roasted asparagus and lemon butter',
    imageUrl: '/images/dishes/grilled-salmon.jpg',
    category: 'dinner',
    difficulty: 2,
    prepTime: 10,
    cookTime: 15,
    instructions: [
      'Preheat grill or oven to 400°F',
      'Season salmon with salt, pepper, and olive oil',
      'Trim asparagus and toss with olive oil, salt, pepper',
      'Grill salmon skin-side down for 6-7 minutes, flip and cook 3-4 more',
      'Roast asparagus for 10-12 minutes until tender',
      'Make lemon butter: melt butter with lemon juice and garlic',
      'Serve salmon and asparagus with lemon butter drizzle',
    ],
    nutrition: { calories: 380, protein: 34, fat: 24, carbs: 8 },
    tags: ['healthy', 'seafood', 'low-carb', 'high-protein'],
    ingredients: [
      { name: 'salmon fillet', amount: '6', unit: 'oz', substitutes: ['trout', 'arctic char'] },
      { name: 'asparagus', amount: '8', unit: 'spears', substitutes: ['green beans', 'broccolini'] },
      { name: 'olive oil', amount: '2', unit: 'tbsp', substitutes: ['avocado oil'] },
      { name: 'butter', amount: '2', unit: 'tbsp', substitutes: ['ghee'] },
      { name: 'lemon juice', amount: '2', unit: 'tbsp', substitutes: ['lime juice'] },
      { name: 'garlic', amount: '2', unit: 'cloves', substitutes: ['garlic powder'] },
      { name: 'salt', amount: '1', unit: 'tsp' },
      { name: 'black pepper', amount: '1/2', unit: 'tsp' },
    ],
  },
  {
    name: 'Beef Tacos with Homemade Salsa',
    description: 'Seasoned ground beef in crispy shells with fresh pico de gallo and toppings',
    imageUrl: '/images/dishes/beef-tacos.jpg',
    category: 'dinner',
    difficulty: 2,
    prepTime: 15,
    cookTime: 15,
    instructions: [
      'Brown ground beef in a large skillet',
      'Add taco seasoning: cumin, chili powder, paprika, garlic',
      'Make pico de gallo: dice tomatoes, onion, jalapeño, cilantro, lime',
      'Warm taco shells in oven',
      'Prepare toppings: shred lettuce and cheese',
      'Assemble tacos with beef, salsa, cheese, lettuce',
      'Serve with lime wedges and sour cream',
    ],
    nutrition: { calories: 480, protein: 28, fat: 24, carbs: 38 },
    tags: ['mexican', 'family-friendly', 'quick'],
    ingredients: [
      { name: 'ground beef', amount: '1', unit: 'lb', substitutes: ['ground turkey', 'ground chicken'] },
      { name: 'taco shells', amount: '8', unit: 'shells', substitutes: ['soft tortillas'] },
      { name: 'tomato', amount: '2', unit: 'medium', substitutes: ['canned diced tomatoes'] },
      { name: 'onion', amount: '1', unit: 'small', substitutes: ['red onion', 'shallot'] },
      { name: 'jalapeño', amount: '1', unit: 'whole', substitutes: ['serrano', 'green chili'] },
      { name: 'cilantro', amount: '1/4', unit: 'cup', substitutes: ['parsley'] },
      { name: 'lime', amount: '2', unit: 'whole', substitutes: ['lemon'] },
      { name: 'lettuce', amount: '2', unit: 'cups', substitutes: ['cabbage'] },
      { name: 'cheddar cheese', amount: '1', unit: 'cup', substitutes: ['monterey jack'] },
      { name: 'cumin', amount: '1', unit: 'tsp' },
      { name: 'chili powder', amount: '1', unit: 'tbsp' },
      { name: 'garlic powder', amount: '1', unit: 'tsp', substitutes: ['fresh garlic'] },
    ],
  },
  {
    name: 'Chicken Stir-Fry',
    description: 'Tender chicken with colorful vegetables in a savory Asian-inspired sauce',
    imageUrl: '/images/dishes/chicken-stir-fry.jpg',
    category: 'dinner',
    difficulty: 2,
    prepTime: 15,
    cookTime: 12,
    instructions: [
      'Cut chicken into bite-sized pieces, season with salt',
      'Prep vegetables: slice bell peppers, broccoli, carrots',
      'Make sauce: soy sauce, oyster sauce, honey, ginger, garlic',
      'Heat wok or large pan with oil on high heat',
      'Stir-fry chicken until cooked, remove from pan',
      'Stir-fry vegetables until crisp-tender',
      'Return chicken, add sauce, toss until coated',
      'Serve over rice',
    ],
    nutrition: { calories: 420, protein: 36, fat: 14, carbs: 38 },
    tags: ['asian', 'quick', 'healthy', 'colorful'],
    ingredients: [
      { name: 'chicken breast', amount: '12', unit: 'oz', substitutes: ['chicken thigh', 'shrimp'] },
      { name: 'bell pepper', amount: '2', unit: 'whole', substitutes: ['snap peas'] },
      { name: 'broccoli', amount: '2', unit: 'cups', substitutes: ['bok choy', 'green beans'] },
      { name: 'carrot', amount: '2', unit: 'medium', substitutes: ['zucchini'] },
      { name: 'soy sauce', amount: '3', unit: 'tbsp', substitutes: ['tamari'] },
      { name: 'oyster sauce', amount: '2', unit: 'tbsp', substitutes: ['hoisin sauce'] },
      { name: 'honey', amount: '1', unit: 'tbsp', substitutes: ['brown sugar'] },
      { name: 'ginger', amount: '1', unit: 'tbsp', substitutes: ['ginger paste'] },
      { name: 'garlic', amount: '3', unit: 'cloves', substitutes: ['garlic paste'] },
      { name: 'vegetable oil', amount: '2', unit: 'tbsp', substitutes: ['peanut oil'] },
      { name: 'white rice', amount: '2', unit: 'cups', substitutes: ['brown rice', 'cauliflower rice'] },
    ],
  },
  {
    name: 'Margherita Pizza',
    description: 'Classic Neapolitan pizza with tomato sauce, fresh mozzarella, and basil',
    imageUrl: '/images/dishes/margherita-pizza.jpg',
    category: 'dinner',
    difficulty: 3,
    prepTime: 90,
    cookTime: 12,
    instructions: [
      'Prepare pizza dough and let rise for 1 hour',
      'Preheat oven to 500°F with pizza stone if available',
      'Roll out dough into 12-inch circle',
      'Spread tomato sauce evenly, leaving 1-inch border',
      'Tear fresh mozzarella and distribute on pizza',
      'Drizzle with olive oil, season with salt',
      'Bake for 10-12 minutes until crust is golden',
      'Top with fresh basil leaves after baking',
    ],
    nutrition: { calories: 580, protein: 24, fat: 20, carbs: 72 },
    tags: ['italian', 'pizza', 'vegetarian', 'classic'],
    ingredients: [
      { name: 'pizza dough', amount: '1', unit: 'lb', substitutes: ['store-bought dough', 'naan bread'] },
      { name: 'tomato sauce', amount: '1/2', unit: 'cup', substitutes: ['crushed tomatoes'] },
      { name: 'fresh mozzarella', amount: '8', unit: 'oz', substitutes: ['regular mozzarella'] },
      { name: 'fresh basil', amount: '10', unit: 'leaves', substitutes: ['dried basil'] },
      { name: 'olive oil', amount: '2', unit: 'tbsp' },
      { name: 'salt', amount: '1', unit: 'tsp' },
      { name: 'garlic', amount: '2', unit: 'cloves', substitutes: ['garlic powder'] },
    ],
  },
  {
    name: 'Thai Red Curry',
    description: 'Creamy coconut curry with chicken, vegetables, and aromatic Thai spices',
    imageUrl: '/images/dishes/thai-curry.jpg',
    category: 'dinner',
    difficulty: 3,
    prepTime: 15,
    cookTime: 25,
    instructions: [
      'Heat oil in large pot, add red curry paste, cook until fragrant',
      'Add coconut milk, bring to simmer',
      'Add chicken pieces, cook for 10 minutes',
      'Add vegetables: bell pepper, bamboo shoots, green beans',
      'Season with fish sauce, brown sugar, lime leaves',
      'Simmer until vegetables are tender',
      'Finish with Thai basil and lime juice',
      'Serve over jasmine rice',
    ],
    nutrition: { calories: 520, protein: 32, fat: 28, carbs: 42 },
    tags: ['thai', 'curry', 'spicy', 'comfort-food'],
    ingredients: [
      { name: 'chicken breast', amount: '12', unit: 'oz', substitutes: ['chicken thigh', 'tofu', 'shrimp'] },
      { name: 'red curry paste', amount: '3', unit: 'tbsp', substitutes: ['green curry paste'] },
      { name: 'coconut milk', amount: '14', unit: 'oz', substitutes: ['light coconut milk'] },
      { name: 'bell pepper', amount: '1', unit: 'whole', substitutes: ['eggplant'] },
      { name: 'bamboo shoots', amount: '1', unit: 'cup', substitutes: ['water chestnuts'] },
      { name: 'green beans', amount: '1', unit: 'cup', substitutes: ['snap peas'] },
      { name: 'fish sauce', amount: '2', unit: 'tbsp', substitutes: ['soy sauce'] },
      { name: 'brown sugar', amount: '1', unit: 'tbsp', substitutes: ['palm sugar', 'white sugar'] },
      { name: 'thai basil', amount: '1/2', unit: 'cup', substitutes: ['regular basil'] },
      { name: 'lime juice', amount: '2', unit: 'tbsp' },
      { name: 'jasmine rice', amount: '2', unit: 'cups', substitutes: ['white rice', 'brown rice'] },
    ],
  },

  // SNACKS
  {
    name: 'Crispy Chicken Wings',
    description: 'Baked chicken wings with buffalo sauce and blue cheese dip',
    imageUrl: '/images/dishes/chicken-wings.jpg',
    category: 'snack',
    difficulty: 2,
    prepTime: 10,
    cookTime: 45,
    instructions: [
      'Pat chicken wings dry, season with salt, pepper, garlic powder',
      'Toss with baking powder for extra crispy skin',
      'Arrange on baking rack, bake at 425°F for 45 minutes',
      'Make buffalo sauce: melt butter with hot sauce',
      'Toss cooked wings in buffalo sauce',
      'Make blue cheese dip: mix blue cheese, sour cream, mayo',
      'Serve with celery sticks',
    ],
    nutrition: { calories: 380, protein: 28, fat: 28, carbs: 4 },
    tags: ['appetizer', 'game-day', 'party'],
    ingredients: [
      { name: 'chicken wings', amount: '2', unit: 'lbs', substitutes: ['drumettes'] },
      { name: 'hot sauce', amount: '1/2', unit: 'cup', substitutes: ['buffalo sauce'] },
      { name: 'butter', amount: '4', unit: 'tbsp', substitutes: ['ghee'] },
      { name: 'blue cheese', amount: '1/2', unit: 'cup', substitutes: ['ranch dressing'] },
      { name: 'sour cream', amount: '1/4', unit: 'cup', substitutes: ['greek yogurt'] },
      { name: 'mayonnaise', amount: '1/4', unit: 'cup' },
      { name: 'baking powder', amount: '1', unit: 'tbsp' },
      { name: 'garlic powder', amount: '1', unit: 'tsp' },
      { name: 'salt', amount: '1', unit: 'tsp' },
      { name: 'celery', amount: '4', unit: 'stalks', substitutes: ['carrots'] },
    ],
  },
  {
    name: 'Guacamole with Chips',
    description: 'Fresh, chunky guacamole with lime, cilantro, and crispy tortilla chips',
    imageUrl: '/images/dishes/guacamole.jpg',
    category: 'snack',
    difficulty: 1,
    prepTime: 10,
    cookTime: 0,
    instructions: [
      'Cut avocados in half, remove pit, scoop into bowl',
      'Mash avocados with fork, leave some chunks',
      'Dice tomato, onion, jalapeño finely',
      'Add lime juice, cilantro, salt to avocado',
      'Mix in diced vegetables',
      'Taste and adjust seasoning',
      'Serve immediately with tortilla chips',
    ],
    nutrition: { calories: 320, protein: 4, fat: 24, carbs: 28 },
    tags: ['mexican', 'vegan', 'quick', 'party'],
    ingredients: [
      { name: 'avocado', amount: '3', unit: 'whole', substitutes: [] },
      { name: 'tomato', amount: '1', unit: 'medium', substitutes: ['cherry tomatoes'] },
      { name: 'red onion', amount: '1/4', unit: 'whole', substitutes: ['white onion'] },
      { name: 'jalapeño', amount: '1', unit: 'small', substitutes: ['serrano'] },
      { name: 'lime juice', amount: '2', unit: 'tbsp', substitutes: ['lemon juice'] },
      { name: 'cilantro', amount: '1/4', unit: 'cup', substitutes: ['parsley'] },
      { name: 'salt', amount: '1', unit: 'tsp' },
      { name: 'tortilla chips', amount: '1', unit: 'bag' },
    ],
  },
  {
    name: 'Hummus Platter',
    description: 'Creamy homemade hummus with olive oil, served with veggies and pita',
    imageUrl: '/images/dishes/hummus.jpg',
    category: 'snack',
    difficulty: 1,
    prepTime: 10,
    cookTime: 0,
    instructions: [
      'Drain and rinse chickpeas',
      'Add chickpeas, tahini, lemon juice, garlic to food processor',
      'Blend while drizzling in ice water until smooth',
      'Season with cumin, salt, paprika',
      'Transfer to serving bowl',
      'Drizzle with olive oil, garnish with paprika and parsley',
      'Serve with pita bread and vegetables',
    ],
    nutrition: { calories: 280, protein: 10, fat: 16, carbs: 26 },
    tags: ['middle-eastern', 'vegan', 'healthy', 'dip'],
    ingredients: [
      { name: 'chickpeas', amount: '15', unit: 'oz', substitutes: ['white beans'] },
      { name: 'tahini', amount: '1/4', unit: 'cup', substitutes: ['almond butter'] },
      { name: 'lemon juice', amount: '3', unit: 'tbsp', substitutes: ['lime juice'] },
      { name: 'garlic', amount: '2', unit: 'cloves', substitutes: ['garlic powder'] },
      { name: 'olive oil', amount: '3', unit: 'tbsp' },
      { name: 'cumin', amount: '1/2', unit: 'tsp' },
      { name: 'paprika', amount: '1/2', unit: 'tsp' },
      { name: 'salt', amount: '1', unit: 'tsp' },
      { name: 'pita bread', amount: '4', unit: 'pieces', substitutes: ['crackers', 'naan'] },
    ],
  },
  {
    name: 'Caprese Skewers',
    description: 'Fresh mozzarella, cherry tomatoes, and basil on skewers with balsamic',
    imageUrl: '/images/dishes/caprese-skewers.jpg',
    category: 'snack',
    difficulty: 1,
    prepTime: 15,
    cookTime: 0,
    instructions: [
      'Thread mozzarella balls onto skewers',
      'Add cherry tomatoes',
      'Top with fresh basil leaves',
      'Arrange on serving platter',
      'Drizzle with balsamic glaze',
      'Season with salt and pepper',
      'Serve immediately or chill',
    ],
    nutrition: { calories: 180, protein: 12, fat: 12, carbs: 8 },
    tags: ['italian', 'vegetarian', 'party', 'elegant'],
    ingredients: [
      { name: 'mozzarella balls', amount: '16', unit: 'pieces', substitutes: ['fresh mozzarella cubes'] },
      { name: 'cherry tomatoes', amount: '16', unit: 'pieces', substitutes: ['grape tomatoes'] },
      { name: 'fresh basil', amount: '16', unit: 'leaves', substitutes: ['arugula'] },
      { name: 'balsamic glaze', amount: '2', unit: 'tbsp', substitutes: ['balsamic vinegar'] },
      { name: 'olive oil', amount: '1', unit: 'tbsp' },
      { name: 'salt', amount: '1', unit: 'pinch' },
      { name: 'black pepper', amount: '1', unit: 'pinch' },
    ],
  },
  {
    name: 'Energy Balls',
    description: 'No-bake energy bites with oats, peanut butter, honey, and chocolate chips',
    imageUrl: '/images/dishes/energy-balls.jpg',
    category: 'snack',
    difficulty: 1,
    prepTime: 15,
    cookTime: 0,
    instructions: [
      'Mix oats, peanut butter, honey in large bowl',
      'Add chocolate chips, chia seeds, vanilla',
      'Stir until well combined',
      'Refrigerate mixture for 30 minutes',
      'Roll into 1-inch balls',
      'Store in airtight container in fridge',
      'Enjoy as pre-workout or afternoon snack',
    ],
    nutrition: { calories: 140, protein: 4, fat: 6, carbs: 18 },
    tags: ['healthy', 'no-bake', 'meal-prep', 'sweet'],
    ingredients: [
      { name: 'rolled oats', amount: '1', unit: 'cup', substitutes: ['quick oats'] },
      { name: 'peanut butter', amount: '1/2', unit: 'cup', substitutes: ['almond butter', 'sunflower seed butter'] },
      { name: 'honey', amount: '1/3', unit: 'cup', substitutes: ['maple syrup', 'agave'] },
      { name: 'chocolate chips', amount: '1/2', unit: 'cup', substitutes: ['dried fruit', 'nuts'] },
      { name: 'chia seeds', amount: '2', unit: 'tbsp', substitutes: ['flax seeds'] },
      { name: 'vanilla extract', amount: '1', unit: 'tsp' },
    ],
  },
];

async function main() {
  console.log('🌱 Starting database seed...');

  // Clear existing data
  console.log('🗑️  Clearing existing data...');
  await prisma.historyEntry.deleteMany({});
  await prisma.favorite.deleteMany({});
  await prisma.ingredient.deleteMany({});
  await prisma.dish.deleteMany({});

  // Seed dishes with ingredients
  console.log('📝 Seeding dishes and ingredients...');
  for (const dishData of dishes) {
    const { ingredients, ...dishFields } = dishData;

    await prisma.dish.create({
      data: {
        ...dishFields,
        instructions: dishFields.instructions,
        nutrition: dishFields.nutrition,
        ingredients: {
          create: ingredients.map((ing) => ({
            name: ing.name,
            amount: ing.amount,
            unit: ing.unit,
            substitutes: ing.substitutes || [],
          })),
        },
      },
    });
  }

  const count = await prisma.dish.count();
  console.log(`✅ Successfully seeded ${count} dishes!`);
}

main()
  .catch((e) => {
    console.error('❌ Error seeding database:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
